### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by aoave** [ga-wdi-exercises/kitchen_organizer#1]
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
cans.txt    fridge      pantry      readme.md
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd fridge
Aurelios-MacBook-Pro:fridge Ao$ ls
diapers.txt freezer     milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
cans.txt    fridge      pantry      readme.md
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd pantry
Aurelios-MacBook-Pro:pantry Ao$ ls
cans.txt    cereal.txt  crisper-drawer
Aurelios-MacBook-Pro:pantry Ao$ mv cripser-drawer ../fridge
mv: rename cripser-drawer to ../fridge/cripser-drawer: No such file or directory
Aurelios-MacBook-Pro:pantry Ao$ ls
cans.txt    cereal.txt  crisper-drawer
Aurelios-MacBook-Pro:pantry Ao$ mv crisper-drawe/../fridge
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Aurelios-MacBook-Pro:pantry Ao$ ls
cans.txt    cereal.txt  crisper-drawer
Aurelios-MacBook-Pro:pantry Ao$ man mv
Aurelios-MacBook-Pro:pantry Ao$ 
Aurelios-MacBook-Pro:pantry Ao$ mv crisper-drawer/ ../fridge
Aurelios-MacBook-Pro:pantry Ao$ ls
cans.txt    cereal.txt
Aurelios-MacBook-Pro:pantry Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
cans.txt    fridge      pantry      readme.md
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd fridge
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ pwd
/Users/Ao/wdi/exercises/kitchen_organizer-master/fridge
Aurelios-MacBook-Pro:fridge Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
cans.txt    fridge      pantry      readme.md
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ mv cans.txt /pantry
mv: rename cans.txt to /pantry: Permission denied
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ man mv
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ mv cans.txt ./pantry/
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd fridge
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ cd freezer
Aurelios-MacBook-Pro:freezer Ao$ ls
couch.txt   frozenpeas.txt  icecream.txt
Aurelios-MacBook-Pro:freezer Ao$ ls
couch.txt   frozenpeas.txt  icecream.txt
Aurelios-MacBook-Pro:freezer Ao$ cd ..
Aurelios-MacBook-Pro:fridge Ao$ cd trashcan
Aurelios-MacBook-Pro:trashcan Ao$ ls
banana-peels.txt    egg-shells.txt
chicken-bones.txt   sink
Aurelios-MacBook-Pro:trashcan Ao$ mv sink ../
Aurelios-MacBook-Pro:trashcan Ao$ ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt
Aurelios-MacBook-Pro:trashcan Ao$ cd ..
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  freezer     sink
diapers.txt milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ cd crisper-drawer/
Aurelios-MacBook-Pro:crisper-drawer Ao$ ls
lettuce.txt
Aurelios-MacBook-Pro:crisper-drawer Ao$ cd ..
Aurelios-MacBook-Pro:fridge Ao$ cd freezer/
Aurelios-MacBook-Pro:freezer Ao$ ls
couch.txt   frozenpeas.txt  icecream.txt
Aurelios-MacBook-Pro:freezer Ao$ cd ..
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  freezer     sink
diapers.txt milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd pantry
Aurelios-MacBook-Pro:pantry Ao$ ls
cans.txt    cereal.txt
Aurelios-MacBook-Pro:pantry Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd fridge/
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  freezer     sink
diapers.txt milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  freezer     sink
diapers.txt milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ cd sink
Aurelios-MacBook-Pro:sink Ao$ ls
clean-dishes.txt    delete-me.txt       dirty-dishes.txt
Aurelios-MacBook-Pro:sink Ao$ cd ..
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  freezer     sink
diapers.txt milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ mv sink/ ..
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md   sink
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd ..
Aurelios-MacBook-Pro:exercises Ao$ ls
command_line_fu-master      kitchen_organizer-master
Aurelios-MacBook-Pro:exercises Ao$ cd kitchen_organizer-master/
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md   sink
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd fridge/
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
Aurelios-MacBook-Pro:fridge Ao$ mv trashcan/ ../
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  diapers.txt freezer     milk.txt
Aurelios-MacBook-Pro:fridge Ao$ rm diapers.txt 
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  freezer     milk.txt
Aurelios-MacBook-Pro:fridge Ao$ cd crisper-drawer/
Aurelios-MacBook-Pro:crisper-drawer Ao$ ls
lettuce.txt
Aurelios-MacBook-Pro:crisper-drawer Ao$ cd ..
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  freezer     milk.txt
Aurelios-MacBook-Pro:fridge Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md   sink        trashcan
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd pantry/
Aurelios-MacBook-Pro:pantry Ao$ ls
cans.txt    cereal.txt
Aurelios-MacBook-Pro:pantry Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md   sink        trashcan
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd sink
Aurelios-MacBook-Pro:sink Ao$ ls
clean-dishes.txt    delete-me.txt       dirty-dishes.txt
Aurelios-MacBook-Pro:sink Ao$ rm delete-me.txt 
Aurelios-MacBook-Pro:sink Ao$ ls
clean-dishes.txt    dirty-dishes.txt
Aurelios-MacBook-Pro:sink Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md   sink        trashcan
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md   sink        trashcan
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd fridge
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  freezer     milk.txt
Aurelios-MacBook-Pro:fridge Ao$ cd crisper-drawer/
Aurelios-MacBook-Pro:crisper-drawer Ao$ ls
lettuce.txt
Aurelios-MacBook-Pro:crisper-drawer Ao$ touch apples.txt
Aurelios-MacBook-Pro:crisper-drawer Ao$ ls
apples.txt  lettuce.txt
Aurelios-MacBook-Pro:crisper-drawer Ao$ cd ..
Aurelios-MacBook-Pro:fridge Ao$ cd freezer/
Aurelios-MacBook-Pro:freezer Ao$ ls
couch.txt   frozenpeas.txt  icecream.txt
Aurelios-MacBook-Pro:freezer Ao$ rm couch.txt 
Aurelios-MacBook-Pro:freezer Ao$ ls
frozenpeas.txt  icecream.txt
Aurelios-MacBook-Pro:freezer Ao$ cd ..
Aurelios-MacBook-Pro:fridge Ao$ ls
crisper-drawer  freezer     milk.txt
Aurelios-MacBook-Pro:fridge Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md   sink        trashcan
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd pantry/
Aurelios-MacBook-Pro:pantry Ao$ ls
cans.txt    cereal.txt
Aurelios-MacBook-Pro:pantry Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md   sink        trashcan
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd trashcan/
Aurelios-MacBook-Pro:trashcan Ao$ ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt
Aurelios-MacBook-Pro:trashcan Ao$ cd ..
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls sink/
clean-dishes.txt    dirty-dishes.txt
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ mkdir drying-rack/
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
drying-rack pantry      sink
fridge      readme.md   trashcan
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ mv drying-rack/ ./sink
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ ls
fridge      pantry      readme.md   sink        trashcan
Aurelios-MacBook-Pro:kitchen_organizer-master Ao$ cd sink
Aurelios-MacBook-Pro:sink Ao$ ls
clean-dishes.txt    dirty-dishes.txt    drying-rack
Aurelios-MacBook-Pro:sink Ao$ mv dirty-dishes.txt ./drying-rack/
Aurelios-MacBook-Pro:sink Ao$ ls
clean-dishes.txt    drying-rack
Aurelios-MacBook-Pro:sink Ao$ cd drying-rack/
Aurelios-MacBook-Pro:drying-rack Ao$ s
-bash: s: command not found
Aurelios-MacBook-Pro:drying-rack Ao$ ls
dirty-dishes.txt
Aurelios-MacBook-Pro:drying-rack Ao$ ls
dirty-dishes.txt
Aurelios-MacBook-Pro:drying-rack Ao$ pwd
/Users/Ao/wdi/exercises/kitchen_organizer-master/sink/drying-rack
Aurelios-MacBook-Pro:drying-rack Ao$ cd ..
Aurelios-MacBook-Pro:sink Ao$ ls
clean-dishes.txt    drying-rack

**Comment by adambray** [comment]
:+1:
