### ISSUE TITLE
Day 1 Homework

### ISSUE THREAD

**Issue by KoryJCampbell** [ga-wdi-exercises/kitchen_organizer#10]
Last login: Mon Oct 12 19:44:12 on ttys000
~ 
$ pwd
/Users/korycampbell
~ 
$ ls
Applications    Downloads   Music       flowers
Desktop     Library     Pictures    wdi
Documents   Movies      Public
~ 
$ cd wdi
~/wdi 
$ ls
Rakefile    exercises   projects
curriculum  installfest.yml sandbox
~/wdi 
$ cd exercies
-bash: cd: exercies: No such file or directory
~/wdi 
$ cd exercises
~/wdi/exercises 
$ ls
kitchen_organizer-master
~/wdi/exercises 
$ cd kitchen_organizer-master
~/wdi/exercises/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/wdi/exercises/kitchen_organizer-master 
$ ls fridge
diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mkdir crisper-drawer
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd crisper-drawer
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ touch apples.txt
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ cd ..
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ man rm
~/wdi/exercises/kitchen_organizer-master 
$ rm -r ~/kitchen_organizer-master/pantry/crisper-drawer
rm: /Users/korycampbell/kitchen_organizer-master/pantry/crisper-drawer: No such file or directory
~/wdi/exercises/kitchen_organizer-master 
$ pwd
/Users/korycampbell/wdi/exercises/kitchen_organizer-master
~/wdi/exercises/kitchen_organizer-master 
$ rm -r ~/kitchen_organizer-master/fridge/pantry/crisper-drawer
rm: /Users/korycampbell/kitchen_organizer-master/fridge/pantry/crisper-drawer: No such file or directory
~/wdi/exercises/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ rm crisper-drawer
rm: crisper-drawer: is a directory
~/wdi/exercises/kitchen_organizer-master/fridge 
$ man rm
~/wdi/exercises/kitchen_organizer-master/fridge 
$ rm -d crisper-drawer
rm: crisper-drawer: Directory not empty
~/wdi/exercises/kitchen_organizer-master/fridge 
$ rm -dr crisper-drawer
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd .. 
~/wdi/exercises/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ..
-bash: ..: command not found
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mkdir crisper-drawer
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd crisper-drawer
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ ls
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ touch apples.txt
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ touch lettuce.txt
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ ls
apples.txt  lettuce.txt
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ cd ..
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ rm diapers.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ rm trashcan
rm: trashcan: is a directory
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv trashcan /..
mv: rename trashcan to /../trashcan: Permission denied
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv trashcan ~/wdi/exercises/kitchen_organizer-master
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls crisper-drawer
apples.txt  lettuce.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls freezer
couch.txt   frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ rm couch.txt
rm: couch.txt: No such file or directory
~/wdi/exercises/kitchen_organizer-master/fridge 
$ rm /freezer/couch.txt
rm: /freezer/couch.txt: No such file or directory
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd freezer
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ ls
couch.txt   frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ rm couch.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ cd ..
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md   trashcan
~/wdi/exercises/kitchen_organizer-master 
$ mv cans.txt ~/wdi/exercises/kitchen_organizer-master/pantry
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd pantry
~/wdi/exercises/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt  crisper-drawer
~/wdi/exercises/kitchen_organizer-master/pantry 
$ rm -dr crisper-drawer
~/wdi/exercises/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt
~/wdi/exercises/kitchen_organizer-master/pantry 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   trashcan
~/wdi/exercises/kitchen_organizer-master 
$ fridge ls
-bash: fridge: command not found
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   trashcan
~/wdi/exercises/kitchen_organizer-master 
$ ls fridge
crisper-drawer  freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master 
$ ls pantry
cans.txt    cereal.txt
~/wdi/exercises/kitchen_organizer-master 
$ ls fridge
crisper-drawer  freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master 
$ ls freezer
ls: freezer: No such file or directory
~/wdi/exercises/kitchen_organizer-master 
$ ls freezer
ls: freezer: No such file or directory
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls freezer
frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd
~ 
$ ls
Applications    Documents   Library     Music       Public      wdi
Desktop     Downloads   Movies      Pictures    flowers
~ 
$ cd wdi
~/wdi 
$ cd exercises
~/wdi/exercises 
$ ls
kitchen_organizer-master
~/wdi/exercises 
$ cd kitchen_organizer-master
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   trashcan
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   trashcan
~/wdi/exercises/kitchen_organizer-master 
$ ls pantry
cans.txt    cereal.txt
~/wdi/exercises/kitchen_organizer-master 
$ mkdir sink
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/exercises/kitchen_organizer-master 
$ ls pantry
cans.txt    cereal.txt
~/wdi/exercises/kitchen_organizer-master 
$ ls fridge
crisper-drawer  freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master 
$ cd sink
~/wdi/exercises/kitchen_organizer-master/sink 
$ touch dirty-dishes.txt
~/wdi/exercises/kitchen_organizer-master/sink 
$ mkdir drying-rack
~/wdi/exercises/kitchen_organizer-master/sink 
$ touch clean-dishes.txt
~/wdi/exercises/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    dirty-dishes.txt    drying-rack
~/wdi/exercises/kitchen_organizer-master/sink 
$ mv clean-dishes.txt ../sink/drying-rack
~/wdi/exercises/kitchen_organizer-master/sink 
$ ls
dirty-dishes.txt    drying-rack
~/wdi/exercises/kitchen_organizer-master/sink 
$ cd drying-rack
~/wdi/exercises/kitchen_organizer-master/sink/drying-rack 
$ ls
clean-dishes.txt
~/wdi/exercises/kitchen_organizer-master/sink/drying-rack 
$ cd ..
~/wdi/exercises/kitchen_organizer-master/sink 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd trashcan
~/wdi/exercises/kitchen_organizer-master/trashcan 
$ ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt      sink
~/wdi/exercises/kitchen_organizer-master/trashcan 
$ rm -dr sink
~/wdi/exercises/kitchen_organizer-master/trashcan 
$ ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/exercises/kitchen_organizer-master/trashcan 
$

**Comment by amaseda** [comment]
:+1:
