### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by roshanad** [ga-wdi-exercises/kitchen_organizer#11]
$ rm cans.txt
$ cd fridge/trashcan/
$ mv sink ../../sink
$ cd ..
$ mv trashcan ../trashcan
$ cd ..
$ cd sink
$ rm delete-me.txt
$ mkdir drying-rack
$ mv clean-dishes.txt drying-rack
$ cd ..
$ cd pantry
$ mv crisper-drawer ../fridge/crisper-drawer
$ cd ..
$ rm diapers.txt
$ cd crisper-drawer/
$ touch apples.txt
$ cd ..
$ cd freezer/
$ rm couch.txt

**Comment by ebirving** [comment]
👍
