### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by beckybeauchamp1** [ga-wdi-exercises/kitchen_organizer#12]
Last login: Mon Oct 12 17:16:04 on ttys000
Hello Becky
~ 
$ cd Downloads
~/Downloads 
$ mv kitchen_organizer-master ../wdi
~/Downloads 
$ cd ../wdi/kitchen_organizer-master
~/wdi/kitchen_organizer-master 
$ rm fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt
~/wdi/kitchen_organizer-master 
$ rm fridge/diapers.txt
~/wdi/kitchen_organizer-master 
$ mv pantry/crisper-drawer fridge/
~/wdi/kitchen_organizer-master 
$ cd fridge
~/wdi/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt    trashcan
~/wdi/kitchen_organizer-master/fridge 
$ cd crisper-drawer
~/wdi/kitchen_organizer-master/fridge/crisper-drawer 
$ ls
lettuce.txt
~/wdi/kitchen_organizer-master/fridge/crisper-drawer 
$ touch apples.txt
~/wdi/kitchen_organizer-master/fridge/crisper-drawer 
$ cd ../freezer
~/wdi/kitchen_organizer-master/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/wdi/kitchen_organizer-master/fridge/freezer 
$ cd ../..
~/wdi/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/wdi/kitchen_organizer-master 
$ mv fridge/tashcan/sink ../../
mv: rename fridge/tashcan/sink to ../../sink: No such file or directory
~/wdi/kitchen_organizer-master 
$ cd fridge
~/wdi/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt    trashcan
~/wdi/kitchen_organizer-master/fridge 
$ mv trashcan/sink ../
~/wdi/kitchen_organizer-master/fridge 
$ mv trashcan ../
~/wdi/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt
~/wdi/kitchen_organizer-master/fridge 
$ cd ..
~/wdi/kitchen_organizer-master 
$ ls
cans.txt    pantry      sink
fridge      readme.md   trashcan
~/wdi/kitchen_organizer-master 
$ mv cans.txt pantry/
~/wdi/kitchen_organizer-master 
$ cd sink
~/wdi/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    dirty-dishes.txt
~/wdi/kitchen_organizer-master/sink 
$ mkdir drying-rack
~/wdi/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    dirty-dishes.txt    drying-rack
~/wdi/kitchen_organizer-master/sink 
$ mv clean-dishes.txt drying-rack/
~/wdi/kitchen_organizer-master/sink 
$ ls
dirty-dishes.txt    drying-rack
~/wdi/kitchen_organizer-master/sink 
$ cd drying-rack
~/wdi/kitchen_organizer-master/sink/drying-rack 
$ ls
clean-dishes.txt
~/wdi/kitchen_organizer-master/sink/drying-rack 
$ cd ..
~/wdi/kitchen_organizer-master/sink 
$ cd ..
~/wdi/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/kitchen_organizer-master 
$ cd pantry
~/wdi/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt
~/wdi/kitchen_organizer-master/pantry 
$ cd ..
~/wdi/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/kitchen_organizer-master 
$ cd ..
~/wdi 
$ ls
Rakefile            kitchen_organizer-master
curriculum          projects
exercises           sandbox
installfest.yml
~/wdi 
$ cd kitchen_organizer-master
~/wdi/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/kitchen_organizer-master 
$ cd trashcan
~/wdi/kitchen_organizer-master/trashcan 
$ ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/kitchen_organizer-master/trashcan 
$ cd ..
~/wdi/kitchen_organizer-master 
$ cd pantry
~/wdi/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt
~/wdi/kitchen_organizer-master/pantry 
$ cd ..
~/wdi/kitchen_organizer-master 
$ cd fridge
~/wdi/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt
~/wdi/kitchen_organizer-master/fridge 
$ cd crisper-drawer
~/wdi/kitchen_organizer-master/fridge/crisper-drawer 
$ ls
apples.txt  lettuce.txt
~/wdi/kitchen_organizer-master/fridge/crisper-drawer 
$ cd ..
~/wdi/kitchen_organizer-master/fridge 
$ cd ..
~/wdi/kitchen_organizer-master 
$ ls -R
fridge      pantry      readme.md   sink        trashcan

./fridge:
crisper-drawer  freezer     milk.txt

./fridge/crisper-drawer:
apples.txt  lettuce.txt

./fridge/freezer:
frozenpeas.txt  icecream.txt

./pantry:
cans.txt    cereal.txt

./sink:
dirty-dishes.txt    drying-rack

./sink/drying-rack:
clean-dishes.txt

./trashcan:
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/kitchen_organizer-master 
$

**Comment by adambray** [comment]
:+1:
