### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by dgorgan** [ga-wdi-exercises/kitchen_organizer#13]
~/Documents/wdi/exercises 

$ mv kitchen_organizer-master/ kitchen

~/Documents/wdi/exercises 

$ cd kitchen/

~/Documents/wdi/exercises/kitchen 

$ rm -r fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt

~/Documents/wdi/exercises/kitchen 

$ mv fridge/trashcan/sink/ fridge/trashcan/ .

~/Documents/wdi/exercises/kitchen 

$ mv pantry/crisper-drawer/ fridge/

~/Documents/wdi/exercises/kitchen 

$ touch fridge/crisper-drawer/apples.txt

~/Documents/wdi/exercises/kitchen 

$ mkdir sink/drying-rack

~/Documents/wdi/exercises/kitchen 

$ mv sink/clean-dishes.txt sink/drying-rack/

~/Documents/wdi/exercises/kitchen 

$ mv cans.txt pantry/
~/Documents/wdi/exercises/kitchen 
$ 

-----------------------------------------=======JUST THE COMMANDS=====--------------------------------------------

$ mv kitchen_organizer-master/ kitchen
$ cd kitchen/
$ rm -r fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt
$ mv fridge/trashcan/sink/ fridge/trashcan/ .
$ mv pantry/crisper-drawer/ fridge/
$ touch fridge/crisper-drawer/apples.txt
$ mkdir sink/drying-rack
$ mv sink/clean-dishes.txt sink/drying-rack/
$ mv cans.txt pantry/

**Comment by ebirving** [comment]
👍
