### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by jacohen10** [ga-wdi-exercises/kitchen_organizer#14]
$ cd kitchen_organizer-master/
$ rm cans.txt fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt
$ mv fridge/trashcan/ .
$ mv trashcan/sink .
$ mv pantry/crisper-drawer/ fridge/
$ touch fridge/crisper-drawer/apples.txt
$ mkdir sink/drying-rack
$ mv sink/clean-dishes.txt sink/drying-rack/

**Comment by amaseda** [comment]
:+1:
