### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by starrchen** [ga-wdi-exercises/kitchen_organizer#15]
rm cans.txt
cd fridge
rm diapers.txt
mv trashcan ..
cd ../pantry
mv crisper-drawer ../fridge
cd ../trashcan/sink
rm delete-me.txt
mkdir drying-rack
mv clean-dishes.txt drying-rack
cd ..
mv sink ..
cd ../fridge/crisper-drawer
touch apples.txt
cd ../freezer
rm couch.txt

**Comment by amaseda** [comment]
:+1:
