### ISSUE TITLE
Day 1 Homework

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/kitchen_organizer#16]
$ mv Downloads/kitchen_organizer-master wdi/exercises/kitchen
~ 
$ cd wdi/exercises/kitchen
~/wdi/exercises/kitchen 
$ rm readme.md cans.txt fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt
~/wdi/exercises/kitchen 
$ mv fridge/trashcan/sink sink
~/wdi/exercises/kitchen 
$ mv fridge/trashcan trashcan
~/wdi/exercises/kitchen 
$ mv pantry/crisper-drawer fridge/crisper-drawer
~/wdi/exercises/kitchen 
$ touch fridge/crisper-drawer/apples.txt
~/wdi/exercises/kitchen 
$ mkdir sink/drying-rack
~/wdi/exercises/kitchen 
$ mv sink/clean-dishes.txt sink/drying-rack/clean-dishes.txt
~/wdi/exercises/kitchen 
$

**Comment by ebirving** [comment]
👍
