### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by matiamin** [ga-wdi-exercises/kitchen_organizer#17]
$ rm -r cans.txt readme.md
$ mv sink ../..
$ rm delete-me.txt
$ mkdir drying-rack
$ mv clean-dishes.txt drying-rack/
$ mv trashcan ..
$ mv crisper-drawer ../fridge/
$ rm diapers.txt 
$ rm couch.txt
$ touch apples.txt

**Comment by adambray** [comment]
:+1:
