### ISSUE TITLE
HW 1 

### ISSUE THREAD

**Issue by MohamedGood** [ga-wdi-exercises/kitchen_organizer#18]
/wdi/exercises/kitchen_organizer (master *) 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/exercises/kitchen_organizer (master *) 
$ cd fridge
~/wdi/exercises/kitchen_organizer/fridge (master *) 
$ ls
crisper-drawer  freezer     milk.txt
~/wdi/exercises/kitchen_organizer/fridge (master *) 
$ cd crisper-drawer
~/wdi/exercises/kitchen_organizer/fridge/crisper-drawer (master *) 
$ ls
apples.txt  lettuce.txt
~/wdi/exercises/kitchen_organizer/fridge/crisper-drawer (master *) 
$ cd ..
~/wdi/exercises/kitchen_organizer/fridge (master *) 
$ cd freezer
~/wdi/exercises/kitchen_organizer/fridge/freezer (master *) 
$ ls
frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer/fridge/freezer (master *) 
$ cd .. 
~/wdi/exercises/kitchen_organizer/fridge (master *) 
$ cd ..
~/wdi/exercises/kitchen_organizer (master *) 
$ cd pantry
~/wdi/exercises/kitchen_organizer/pantry (master *) 
$ ls
cans.txt    cereal.txt
~/wdi/exercises/kitchen_organizer/pantry (master *) 
$ cd ..
~/wdi/exercises/kitchen_organizer (master *) 
$ cd sink
~/wdi/exercises/kitchen_organizer/sink (master *) 
$ ls
dirty-dishes.txt    drying-rack
~/wdi/exercises/kitchen_organizer/sink (master *) 
$ cd drying-rack
~/wdi/exercises/kitchen_organizer/sink/drying-rack (master *) 
$ ls
clean-dishes.txt
~/wdi/exercises/kitchen_organizer/sink/drying-rack (master *) 
$ cd ..
~/wdi/exercises/kitchen_organizer/sink (master *) 
$ cd trashcan
-bash: cd: trashcan: No such file or directory
~/wdi/exercises/kitchen_organizer/sink (master *) 
$ cd ..
~/wdi/exercises/kitchen_organizer (master *) 
$ cd trashcan
~/wdi/exercises/kitchen_organizer/trashcan (master *) 
$ ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/exercises/kitchen_organizer/trashcan (master *) 
$

**Comment by ebirving** [comment]
👍
