### ISSUE TITLE
Day 2 HW

### ISSUE THREAD

**Issue by ascreven** [ga-wdi-exercises/kitchen_organizer#19]
~/wdi/exercises/Week1/cli/kitchen_organizer-master (master *#) 
$ rm fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt 
~/wdi/exercises/Week1/cli/kitchen_organizer-master (master *#) 
$ mv fridge/trashcan/ .
~/wdi/exercises/Week1/cli/kitchen_organizer-master (master *#) 
$ mv pantry/crisper-drawer/ fridge/
~/wdi/exercises/Week1/cli/kitchen_organizer-master (master *#) 
$ touch fridge/crisper-drawer/apples.txt
~/wdi/exercises/Week1/cli/kitchen_organizer-master (master *#) 
$ mv cans.txt pantry/
~/wdi/exercises/Week1/cli/kitchen_organizer-master (master *#) 
$ mkdir trashcan/sink/drying-rack
~/wdi/exercises/Week1/cli/kitchen_organizer-master (master *#) 
$ mv trashcan/sink/ .
~/wdi/exercises/Week1/cli/kitchen_organizer-master (master *#) 
$ mv sink/clean-dishes.txt sink/drying-rack/
~/wdi/exercises/Week1/cli/kitchen_organizer-master (master *#) 
$

**Comment by mattscilipoti** [comment]
:+1:
