### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by jordanbrauner** [ga-wdi-exercises/kitchen_organizer#2]
Last login: Mon Oct 12 16:58:07 on ttys000
~ 
$ cd wdi/exercises/kitchen_organizer-master/
~/wdi/exercises/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/wdi/exercises/kitchen_organizer-master 
$ rm cans.txt fridge/diapers.txt fridge/trashcan/sink/delete-me.txt fridge/freezer/couch.txt
~/wdi/exercises/kitchen_organizer-master 
$ mv pantry/crisper-drawer fridge
~/wdi/exercises/kitchen_organizer-master 
$ mv fridge/trashcan .
~/wdi/exercises/kitchen_organizer-master 
$ mv trashcan/sink .
~/wdi/exercises/kitchen_organizer-master 
$ touch fridge/crisper-drawer/apples.txt
~/wdi/exercises/kitchen_organizer-master 
$ mkdir sink/drying-rack
~/wdi/exercises/kitchen_organizer-master 
$ mv sink/clean-dishes.txt sink/drying-rack
~/wdi/exercises/kitchen_organizer-master 

/\* COMMANDS */

rm cans.txt fridge/diapers.txt fridge/trashcan/sink/delete-me.txt fridge/freezer/couch.txt
mv pantry/crisper-drawer fridge
mv fridge/trashcan .
mv trashcan/sink .
touch fridge/crisper-drawer/apples.txt
mkdir sink/drying-rack
mv sink/clean-dishes.txt sink/drying-rack

**Comment by amaseda** [comment]
:+1:
