### ISSUE TITLE
Kitchen_Organizer HW1

### ISSUE THREAD

**Issue by yinkaagiri** [ga-wdi-exercises/kitchen_organizer#20]
$ rm -r cans.txt
~/downloads/kitchen_organizer (master *) 
$ rm -r readme.md
~/downloads/kitchen_organizer (master *) 
$ cd fridge
~/downloads/kitchen_organizer/fridge (master *) 
$ rm -r diapers.txt trashcan
~/downloads/kitchen_organizer/fridge (master *) 
$ mkdir crisper-drawer
~/downloads/kitchen_organizer/fridge (master *) 
$ cd crisper-drawer
~/downloads/kitchen_organizer/fridge/crisper-drawer (master *) 
$ touch apples.txt lettuce.txt
~/downloads/kitchen_organizer/fridge/crisper-drawer (master *) 
$ cd ..
~/downloads/kitchen_organizer/fridge (master *) 
$ cd freezer
~/downloads/kitchen_organizer/fridge/freezer (master *) 
$ rm -r couch.txt
~/downloads/kitchen_organizer/fridge/freezer (master *) 
$ cd ..
~/downloads/kitchen_organizer/fridge (master *) 
$ cd ..
~/downloads/kitchen_organizer (master *) 
$ mkdir sink trashcan
~/downloads/kitchen_organizer (master *) 
$ cd pantry
~/downloads/kitchen_organizer/pantry (master *) 
$ rm -r crisper-drawer
~/downloads/kitchen_organizer/pantry (master *) 
$ cd ..
~/downloads/kitchen_organizer (master *) 
$ cd sink
~/downloads/kitchen_organizer/sink (master *) 
$ touch dirty-dishes.txt clean-dishes.txt
~/downloads/kitchen_organizer/sink (master *) 
$ mkdir drying-rack
~/downloads/kitchen_organizer/sink (master *) 
$ mv clean-dishes.txt drying-rack
~/downloads/kitchen_organizer/sink (master *) 
$ cd drying-rack
~/downloads/kitchen_organizer/sink/drying-rack (master *) 
$ cd ..
$ cd trashcan
 $ touch banana-peels.txt chicken-bones.txt egg-shells.txt

**Comment by adambray** [comment]
:+1:
