### ISSUE TITLE
Homework day 1 CLI

### ISSUE THREAD

**Issue by kaustly** [ga-wdi-exercises/kitchen_organizer#21]
Gardening:
Last login: Tue Oct 13 15:34:17 on ttys000
~ 
$ cd ~
~ 
$ ls
Applications    Downloads   Music       World
Conduit     Fundamentals    Pictures    World.zip
Desktop     Library     Public      funny_things
Documents   Movies      PycharmProjects wdi
~ 
$ mkdir flowers
~ 
$ cd flowers
~/flowers 
$ mkdir petunia
~/flowers 
$ mkdir violet
~/flowers 
$ mkdir marigold
~/flowers 
$ mkdir seeds
~/flowers 
$ ls
marigold    petunia     seeds       violet
~/flowers 
$ cd violet
~/flowers/violet 
$ touch marigold-seeds.txt marigoldfood.txt violet-seeds.txt petunia-bulbs.txt
~/flowers/violet 
$ ls
marigold-seeds.txt  petunia-bulbs.txt
marigoldfood.txt    violet-seeds.txt
~/flowers/violet 
$ cp marigold-seeds.txt marigoldfood.txt ../marigold
~/flowers/violet 
$ ls
marigold-seeds.txt  petunia-bulbs.txt
marigoldfood.txt    violet-seeds.txt
~/flowers/violet 
$ cd ..
~/flowers 
$ ls
marigold    petunia     seeds       violet
~/flowers 
$ cd marigold
~/flowers/marigold 
$ ls
marigold-seeds.txt  marigoldfood.txt
~/flowers/marigold 
$ cd ..
~/flowers 
$ cd marigold
~/flowers/marigold 
$ ls
marigold-seeds.txt  marigoldfood.txt
~/flowers/marigold 
$ mv marigold-seeds ~/flowers/seeds/marigold-seeds.txt
mv: rename marigold-seeds to /Users/kaustly/flowers/seeds/marigold-seeds.txt: No such file or directory
~/flowers/marigold 
$ mv marigold-seeds.txt ~/flowers/seeds/marigold-seeds.txt
~/flowers/marigold 
$ cd ..
~/flowers 
$ ls
marigold    petunia     seeds       violet
~/flowers 
$ cd violet 
~/flowers/violet 
$ ls
marigold-seeds.txt  petunia-bulbs.txt
marigoldfood.txt    violet-seeds.txt
~/flowers/violet 
$ mv violet-seeds.txt ~/flowers/seeds/violet-seeds.txt
~/flowers/violet 
$ ls
marigold-seeds.txt  marigoldfood.txt    petunia-bulbs.txt
~/flowers/violet 
$ mv marigold-seeds.txt ~/flowers/seeds/marigold-seeds.txt 
~/flowers/violet 
$ lds
-bash: lds: command not found
~/flowers/violet 
$ ls
marigoldfood.txt    petunia-bulbs.txt
~/flowers/violet 
$ mv petunia-bulbs.txt ~/flowers/seeds/petunia-bulbs.txt
~/flowers/violet 
$ ls
marigoldfood.txt
~/flowers/violet 
$ cd ..
~/flowers 
$ ls
marigold    petunia     seeds       violet
~/flowers 
$ cp -r marigold ~/flowers/petunia
~/flowers 
$ cd petunia
~/flowers/petunia 
$ ls
marigold
~/flowers/petunia 
$ cd marigold
~/flowers/petunia/marigold 
$ ls
marigoldfood.txt
~/flowers/petunia/marigold 
$ mv marigoldfood.txt ~/flowers/petunia/petunia-food.txt
~/flowers/petunia/marigold 
$ ls
~/flowers/petunia/marigold 
$ 

Kitchen:
Last login: Tue Oct 13 15:41:24 on ttys000
~ 
$ cd
~ 
$ pwd
/Users/kaustly
~ 
$ ls
Applications    Downloads   Music       World       wdi
Conduit     Fundamentals    Pictures    World.zip
Desktop     Library     Public      flowers
Documents   Movies      PycharmProjects funny_things
~ 
$ cd downloads
~/downloads 
$ ls
2014TaxReturn.PDF
Atom.app
BFA
Downloader_setup_mac (1).dmg
GA
GitHub Desktop 212.zip
GoldMosh2
IMG_0687_converted.png
IMG_4225.png
One-Stop Datamosh Kit
Spectacle+1.0.1.zip
Sublime Text 2.0.2.dmg
Techshop - Kelly Austin Paystub 6.15.pdf
Techshop - Kelly Austin Paystub 6.30-1.pdf
Techshop - Kelly Austin Paystub 6.30.pdf
adobe_flashplayer_e2c7b_Setup.dmg
atom-mac.zip
cli_gardening-master
cli_gardening-master.zip
documents-export-2014-11-22 3
flashplayerformacch-gal.dmg
git-2.2.1-intel-universal-snow-leopard.dmg
git-2.5.3-intel-universal-mavericks.dmg
hello-rename.txt
kitchen_organizer-master
kitchen_organizer-master.zip
pycharm-edu-2.dmg
slack-1.1.4.zip
socicon-v1.3.zip
~/downloads 
$ mv kitchen_organizer-master ~
~/downloads 
$ cd ~
~ 
$ ls
Applications            Pictures
Conduit             Public
Desktop             PycharmProjects
Documents           World
Downloads           World.zip
Fundamentals            flowers
Library             funny_things
Movies              kitchen_organizer-master
Music               wdi
~ 
$ cd kitchen_organizer-master/
~/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/kitchen_organizer-master 
$ cd fridge
~/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/kitchen_organizer-master/fridge 
$ mv milk ..
mv: rename milk to ../milk: No such file or directory
~/kitchen_organizer-master/fridge 
$ mv milk.txt ..
~/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     trashcan
~/kitchen_organizer-master/fridge 
$ mv trashcan 
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/kitchen_organizer-master/fridge 
$ mv trashcan ~/kitchen_organizer-master/
~/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer
~/kitchen_organizer-master/fridge 
$ rm diapers.txt
~/kitchen_organizer-master/fridge 
$ ls
freezer
~/kitchen_organizer-master/fridge 
$ cd freezer
~/kitchen_organizer-master/fridge/freezer 
$ ls
couch.txt   frozenpeas.txt  icecream.txt
~/kitchen_organizer-master/fridge/freezer 
$ rm couch.txt
~/kitchen_organizer-master/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/kitchen_organizer-master/fridge/freezer 
$ cd ..
~/kitchen_organizer-master/fridge 
$ ls
freezer
~/kitchen_organizer-master/fridge 
$ cd ..
~/kitchen_organizer-master 
$ ls
cans.txt    milk.txt    readme.md
fridge      pantry      trashcan
~/kitchen_organizer-master 
$ mv milk.txt ~/kitchen_organizer-master/fridge/milk.txt
~/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md   trashcan
~/kitchen_organizer-master 
$ cd trashcan/
~/kitchen_organizer-master/trashcan 
$ ls
banana-peels.txt    egg-shells.txt
chicken-bones.txt   sink
~/kitchen_organizer-master/trashcan 
$ mv sink ..
~/kitchen_organizer-master/trashcan 
$ ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/kitchen_organizer-master/trashcan 
$ cd ..
~/kitchen_organizer-master 
$ ls
cans.txt    pantry      sink
fridge      readme.md   trashcan
~/kitchen_organizer-master 
$ mv cans.txt ~/kitchen_organizer-master/pantry/cans.txt
~/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/kitchen_organizer-master 
$ cd fridge
~/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt
~/kitchen_organizer-master/fridge 
$ cd ..
~/kitchen_organizer-master 
$ cd pantry
~/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt  crisper-drawer
~/kitchen_organizer-master/pantry 
$ mv crisper-drawer ~/kitchen_organizer-master/fridge
~/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt
~/kitchen_organizer-master/pantry 
$ cd ..
~/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/kitchen_organizer-master 
$ cd sink
~/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    delete-me.txt       dirty-dishes.txt
~/kitchen_organizer-master/sink 
$ rm delete-me.txt
~/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    dirty-dishes.txt
~/kitchen_organizer-master/sink 
$ cd ..
~/kitchen_organizer-master 
$ cd fridge
~/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt
~/kitchen_organizer-master/fridge 
$ cd crisper-drawer
~/kitchen_organizer-master/fridge/crisper-drawer 
$ ls
lettuce.txt
~/kitchen_organizer-master/fridge/crisper-drawer 
$ touch apples.txt
~/kitchen_organizer-master/fridge/crisper-drawer 
$ 

comfort: 3.7
completeness: 4.7...?

Coments: Can we go over how to apply commands to multiple directories or files within one line?

**Comment by adambray** [comment]
Hey Kelly, this looks pretty good!

To Answer your question about applying commands to multiple directories, it's probably easier to demo in person. Feel free to find me during a break (or when I'm doing office hours Wed at lunch or Thurs evening) and we can go over the common cases.

-Adam
