### ISSUE TITLE
Day 2 HW

### ISSUE THREAD

**Issue by estennett** [ga-wdi-exercises/kitchen_organizer#22]
Comfort: 4
Completeness: 5

$ mv cans.txt ./pantry
$ rm ./fridge/diapers.txt ./fridge/freezer/couch.txt 
$ mv ./pantry/crisper-drawer/ ./fridge/
$ touch ./fridge/crisper-drawer/apples.txt
$ mkdir ./sink/drying-rack
$ mv ./sink/clean-dishes.txt ./sink/drying-rack/
$ rm ./sink/delete-me.txt

There were several LS commands in there, not sure if they count.

**Comment by nolds9** [comment]
:+1:
