### ISSUE TITLE
Day 1 HW Kitchen 

### ISSUE THREAD

**Issue by Cajam** [ga-wdi-exercises/kitchen_organizer#23]
[CassCD~/wdi]$ cd kitchen_organizer
[CassCD~/wdi/kitchen_organizer]$ 
[CassCD~/wdi/kitchen_organizer]$ ls
cans.txt    fridge      pantry      readme.md
[CassCD~/wdi/kitchen_organizer]$ cd pantry
[CassCD~/wdi/kitchen_organizer/pantry]$ mv crisper-drawer ~/wdi/kitchen_organizer/fridge
[CassCD~/wdi/kitchen_organizer/pantry]$ cd ..
[CassCD~/wdi/kitchen_organizer]$ mv cans.txt pantry
[CassCD~/wdi/kitchen_organizer]$ cd fridge
[CassCD~/wdi/kitchen_organizer/fridge]$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
[CassCD~/wdi/kitchen_organizer/fridge]$ mv trashcan ..
[CassCD~/wdi/kitchen_organizer/fridge]$ ls
crisper-drawer  diapers.txt freezer     milk.txt
[CassCD~/wdi/kitchen_organizer/fridge]$ rm diapers.txt
[CassCD~/wdi/kitchen_organizer/fridge]$ cd freezer
[CassCD~/wdi/kitchen_organizer/fridge/freezer]$ rm couch.txt
[CassCD~/wdi/kitchen_organizer/fridge/freezer]$ ls
frozenpeas.txt  icecream.txt
[CassCD~/wdi/kitchen_organizer/fridge/freezer]$ cd ..
[CassCD~/wdi/kitchen_organizer/fridge]$ ls
crisper-drawer  freezer     milk.txt
[CassCD~/wdi/kitchen_organizer/fridge]$ cd crisper-drawer
[CassCD~/wdi/kitchen_organizer/fridge/crisper-drawer]$ touch apples.txt
[CassCD~/wdi/kitchen_organizer/fridge/crisper-drawer]$ ls
apples.txt  lettuce.txt
[CassCD~/wdi/kitchen_organizer/fridge/crisper-drawer]$ cd ..
[CassCD~/wdi/kitchen_organizer/fridge]$ cd ..
[CassCD~/wdi/kitchen_organizer]$ ls
fridge      pantry      readme.md   trashcan
[CassCD~/wdi/kitchen_organizer]$ cd pantry
[CassCD~/wdi/kitchen_organizer/pantry]$ ls
cans.txt    cereal.txt
[CassCD~/wdi/kitchen_organizer/pantry]$ cd ..
[CassCD~/wdi/kitchen_organizer]$ cd trashcan
[CassCD~/wdi/kitchen_organizer/trashcan]$ ls
banana-peels.txt    egg-shells.txt
chicken-bones.txt   sink
[CassCD~/wdi/kitchen_organizer/trashcan]$ rm sink
rm: sink: is a directory
[CassCD~/wdi/kitchen_organizer/trashcan]$ ls
banana-peels.txt    egg-shells.txt
chicken-bones.txt   sink
[CassCD~/wdi/kitchen_organizer/trashcan]$ rmdir sink
rmdir: sink: Directory not empty
[CassCD~/wdi/kitchen_organizer/trashcan]$ rm -rf sink
[CassCD~/wdi/kitchen_organizer/trashcan]$ ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt
[CassCD~/wdi/kitchen_organizer/trashcan]$ cd ..
[CassCD~/wdi/kitchen_organizer]$ ls
fridge      pantry      readme.md   trashcan
[CassCD~/wdi/kitchen_organizer]$ mkdir sink
[CassCD~/wdi/kitchen_organizer]$ cd sink
[CassCD~/wdi/kitchen_organizer/sink]$ touch  dirty-dishes.txt
[CassCD~/wdi/kitchen_organizer/sink]$ mkdir drying-rack
[CassCD~/wdi/kitchen_organizer/sink]$ cd drying-rack
[CassCD~/wdi/kitchen_organizer/sink/drying-rack]$ touch clean-dishes.txt

**Comment by jshawl** [comment]
:+1: Looks good! be sure to use backticks in the future to format code:

```
[CassCD~/wdi/kitchen_organizer/sink]$ mkdir drying-rack
[CassCD~/wdi/kitchen_organizer/sink]$ cd drying-rack
[CassCD~/wdi/kitchen_organizer/sink/drying-rack]$ touch clean-dishes.txt
```
