### ISSUE TITLE
Kitchen Organizer HW

### ISSUE THREAD

**Issue by elisekain** [ga-wdi-exercises/kitchen_organizer#24]
completeness: 5
comfort_level: 4

$ cd kitchen_organizer/
$ rm fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt
~/wdi/homework/hw1_cli_kitchen/kitchen_organizer (master *) 
$ mv fridge/trashcan/ .
~/wdi/homework/hw1_cli_kitchen/kitchen_organizer (master *) 
$ mv trashcan/sink/ .
~/wdi/homework/hw1_cli_kitchen/kitchen_organizer (master *) 
$ mv cans.txt pantry
~/wdi/homework/hw1_cli_kitchen/kitchen_organizer (master *) 
$ mv pantry/crisper-drawer/ fridge
~/wdi/homework/hw1_cli_kitchen/kitchen_organizer (master *) 
$ touch fridge/crisper-drawer/apples.txt
~/wdi/homework/hw1_cli_kitchen/kitchen_organizer (master *) 
$ mkdir sink/drying-rack
~/wdi/homework/hw1_cli_kitchen/kitchen_organizer (master *) 
$ mv sink/clean-dishes.txt sink/drying-rack/
~/wdi/homework/hw1_cli_kitchen/kitchen_organizer (master *)

**Comment by jsm13** [comment]
:+1:
