### ISSUE TITLE
CLI homework

### ISSUE THREAD

**Issue by pzhang87** [ga-wdi-exercises/kitchen_organizer#25]
comfort: 4
completeness: 5

rm cans.txt fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt
mv fridge/trashcan/sink fridge/trashcan .

mkdir sink/drying-rack
mv sink/clean-dishes.txt sink/drying-rack/

mv pantry/crisper-drawer/ fridge
touch fridge/crisper-drawer/apples.txt

**Comment by nolds9** [comment]
:+1:
