### ISSUE TITLE
CLI HW

### ISSUE THREAD

**Issue by schersh** [ga-wdi-exercises/kitchen_organizer#26]
➜  kitchen_organizer git:(master) ls
cans.txt  fridge    pantry    readme.md
➜  kitchen_organizer git:(master) rm cans.txt 
➜  kitchen_organizer git:(master) ✗ cd pantry 
➜  pantry git:(master) ✗ mv crisper-drawer ../fridge 
➜  pantry git:(master) ✗ cd ../fridge 
➜  fridge git:(master) ✗ ls
crisper-drawer diapers.txt    freezer        milk.txt       trashcan
➜  fridge git:(master) ✗ rm diapers.txt 
➜  fridge git:(master) ✗ mv trashcan .. 
➜  fridge git:(master) ✗ cd ..
➜  kitchen_organizer git:(master) ✗ cd trashcan 
➜  trashcan git:(master) ✗ mv sink ..
➜  trashcan git:(master) ✗ cd ../sink 
➜  sink git:(master) ✗ rm delete-me.txt 
➜  sink git:(master) ✗ mkdir drying-rack
➜  sink git:(master) ✗ mv clean-dishes.txt drying-rack 
➜  sink git:(master) ✗ cd ../fridge/freezer 
➜  freezer git:(master) ✗ rm couch.txt 
➜  freezer git:(master) ✗ cd ..
➜  fridge git:(master) ✗ cd crisper-drawer 
➜  crisper-drawer git:(master) ✗ touch apples.txt 
➜  crisper-drawer git:(master) ✗ ls
apples.txt  lettuce.txt
➜  crisper-drawer git:(master) ✗ cd .. 
➜  fridge git:(master) ✗ cd ..
➜  kitchen_organizer git:(master) ✗ ls
fridge    pantry    readme.md sink      trashcan
➜  kitchen_organizer git:(master) ✗

**Comment by jshawl** [comment]
:+1: Cool to see you using zsh! are you using any plugins or a cool theme I should check out?

also please use backticks in the future to format code:

```
➜ kitchen_organizer git:(master) ✗ ls
fridge pantry readme.md sink trashcan
➜ kitchen_organizer git:(master) ✗
```
