### ISSUE TITLE
CLI HW

### ISSUE THREAD

**Issue by cpgruber** [ga-wdi-exercises/kitchen_organizer#28]
cd kitchen_organizer
~/wdi/kitchen_organizer (master) 
$ mv fridge/trashcan .
~/wdi/kitchen_organizer (master *)
$ mv trashcan/sink .
~/wdi/kitchen_organizer (master *)
$ mv pantry/crisper-drawer/ fridge
~/wdi/kitchen_organizer (master *)
$ touch fridge/crisper-drawer/apples.txt
~/wdi/kitchen_organizer (master *)
$ rm fridge/freezer/couch.txt
~/wdi/kitchen_organizer (master *)
$ rm fridge/diapers.txt
~/wdi/kitchen_organizer (master *)
$ mv cans.txt pantry/
~/wdi/kitchen_organizer (master *)
$ rm sink/delete-me.txt
~/wdi/kitchen_organizer (master *)
$ mkdir sink/drying-rack
~/wdi/kitchen_organizer (master *)
$ mv sink/clean-dishes.txt sink/drying-rack/

**Comment by jshawl** [comment]
:+1: Looks great! Please use backticks in the future to format code:

```
~/wdi/kitchen_organizer (master *)
$ mv sink/clean-dishes.txt sink/drying-rack/
```
