### ISSUE TITLE
Day 1 Homework 

### ISSUE THREAD

**Issue by mcgrodsky** [ga-wdi-exercises/kitchen_organizer#29]
rm cans.txt
cd fridge
rm diapers.txt
mv trashcan ..
cd ../pantry
mv crisper-drawer /fridge
cd..
cd trashcan/
cd sink/
rm delete-me.txt
mkdir drying-rack
mv clean-dishes.txt drying-rack
cd ..
mv sink ..
cd ../fridge/crisper-drawer
touch apples.txt
cd ../freezer
rm couch.txt

**Comment by jshawl** [comment]
:+1: please use backticks in the future to format code:

```
cd trashcan/
rm delete-me.txt
```
