### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by toryburgett** [ga-wdi-exercises/kitchen_organizer#3]
Last login: Mon Oct 12 14:19:53 on ttys000
~ 
$ pwd
/Users/ToryBurgett
~ 
$ ls
Applications    Downloads   Music       World       wdi
Desktop     Library     Pictures    fundamentals
Documents   Movies      Public      funny_things
~ 
$ cd wdi/exercises
~/wdi/exercises 
$ rm -r kitchen_organizer-master/
~/wdi/exercises 
$ mv ~/Downloads/kitchen_organizer-master ~/wdi/exercises/
~/wdi/exercises 
$ mkdir kitchen_organizer-master/kitchen
~/wdi/exercises 
$ mv kitchen_organizer-master/cans.txt kitchen_organizer-master/fridge/ kitchen_organizer-master/pantry/ kitchen_organizer-master/kitchen/
~/wdi/exercises 
$ mv kitchen_organizer-master/kitchen/fridge/trashcan/ kitchen_organizer-master/kitchen/
~/wdi/exercises 
$ mv kitchen_organizer-master/kitchen/trashcan/sink/ kitchen_organizer-master/kitchen/
~/wdi/exercises 
$ mv kitchen_organizer-master/kitchen/pantry/crisper-drawer/ kitchen_organizer-master/kitchen/fridge/
~/wdi/exercises 
$ mv kitchen_organizer-master/kitchen/cans.txt kitchen_organizer-master/kitchen/pantry/
~/wdi/exercises 
$ mkdir kitchen_organizer-master/kitchen/sink/drying-rack
~/wdi/exercises 
$ mv kitchen_organizer-master/kitchen/sink/clean-dishes.txt kitchen_organizer-master/kitchen/sink/drying-rack/
~/wdi/exercises 
$ rm kitchen_organizer-master/kitchen/sink/delete-me.txt 
~/wdi/exercises 
$ rm kitchen_organizer-master/kitchen/fridge/diapers.txt 
~/wdi/exercises 
$ rm kitchen_organizer-master/kitchen/fridge/freezer/couch.txt 
~/wdi/exercises 
$ touch kitchen_organizer-master/kitchen/fridge/crisper-drawer/apples.txt
~/wdi/exercises 
$ open .
~/wdi/exercises

**Comment by amaseda** [comment]
:+1:
