### ISSUE TITLE
Day 1 HW 

### ISSUE THREAD

**Issue by solowt** [ga-wdi-exercises/kitchen_organizer#31]
mv cans.txt pantry
rm fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt
mv fridge/trashcan/sink fridge/trashcan -t .
mv pantry/crisper-drawer fridge
mkdir sink/drying-rack
touch fridge/crisper-drawer/apples.txt
mv sink/clean-dishes.txt sink/drying-rack

**Comment by nolds9** [comment]
:+1:
