### ISSUE TITLE
Murgia Kitchen HW

### ISSUE THREAD

**Issue by murgia** [ga-wdi-exercises/kitchen_organizer#32]
$ pwd
/Users/Matthew/wdi/exercises/kitchen_organizer-master/fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/wdi/exercises/kitchen_organizer-master 
$ rm cans.txt
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv -R trashcan ..
mv: illegal option -- R
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv trashcan ..
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd trashcan
~/wdi/exercises/kitchen_organizer-master/trashcan 
$ ls
banana-peels.txt    egg-shells.txt
chicken-bones.txt   sink
~/wdi/exercises/kitchen_organizer-master/trashcan 
$ mv sink ..
~/wdi/exercises/kitchen_organizer-master/trashcan 
$ lx
-bash: lx: command not found
~/wdi/exercises/kitchen_organizer-master/trashcan 
$ ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/exercises/kitchen_organizer-master/trashcan 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ rm diapers.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd freezer
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ ls
couch.txt   frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ rm couch.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ cd ..
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd sink
~/wdi/exercises/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    delete-me.txt       dirty-dishes.txt
~/wdi/exercises/kitchen_organizer-master/sink 
$ rm delete-me.txt
~/wdi/exercises/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    dirty-dishes.txt
~/wdi/exercises/kitchen_organizer-master/sink 
$ mkdir drying-rack
~/wdi/exercises/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    dirty-dishes.txt    drying-rack
~/wdi/exercises/kitchen_organizer-master/sink 
$ mv clean-dishes.txt drying-rack/
~/wdi/exercises/kitchen_organizer-master/sink 
$ ls
dirty-dishes.txt    drying-rack
~/wdi/exercises/kitchen_organizer-master/sink 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd pantry
~/wdi/exercises/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt  crisper-drawer
~/wdi/exercises/kitchen_organizer-master/pantry 
$ mv crisper-drawer/ ~/wdi/exercises/kitchen_organizer-master/
.DS_Store  fridge/    pantry/    readme.md  sink/      trashcan/  
~/wdi/exercises/kitchen_organizer-master/pantry 
$ mv crisper-drawer/ ~/wdi/exercises/kitchen_organizer-master/fridge/
~/wdi/exercises/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt
~/wdi/exercises/kitchen_organizer-master/pantry 
$ cd ..
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge/
crisper-drawer/ freezer/  
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge/
crisper-drawer/ freezer/  
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge/crisper-drawer/
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ touch apples.txt
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ ls
apples.txt  lettuce.txt
~/wdi/exercises/kitchen_organizer-master/fridge/crisper-drawer 
$ 

Comfort Level: 4
Completeness: 5

**Comment by andrewsunglaekim** [comment]
:+1:
