### ISSUE TITLE
CLI HW

### ISSUE THREAD

**Issue by Chauncey1989** [ga-wdi-exercises/kitchen_organizer#33]
mv sink kitchen
mv trashcan kitchen
rm diapers.txt delete me.txt couch.txt
mv crisper-drawer fridge
mv apples.txt lettuce.txt ~/crisper drawer
mv banana-peels.txt chicken-bones.txt egg-shells.txt ~/trashcan
mv milk.txt ~/fridge
mv dirty-dishes.txt sink
mkdir drying-rack
mv drying-rack sink
mv clean-dishes.txt drying rack

**Comment by RobertAKARobin** [comment]
:+1:
