### ISSUE TITLE
Day 1 Homework(Brendan Mahoney)

### ISSUE THREAD

**Issue by BMahoney08** [ga-wdi-exercises/kitchen_organizer#34]
~/Desktop/homework/kitchen_organizer (master) 
$ mv cans.txt pantry/

~/Desktop/homework/kitchen_organizer (master *) 
$ l

---

.git/
fridge/
pantry/
## readme.md

~/Desktop/homework/kitchen_organizer (master *) 
$ l

---

.git/
fridge/
pantry/
## readme.md

~/Desktop/homework/kitchen_organizer (master *) 
$ cd fridge
~/Desktop/homework/kitchen_organizer/fridge (master *) 
$ mv trashcan/ ../
~/Desktop/homework/kitchen_organizer/fridge (master *) 
$ cd trashcan
-bash: cd: trashcan: No such file or directory
~/Desktop/homework/kitchen_organizer/fridge (master *) 
$ cd ..
~/Desktop/homework/kitchen_organizer (master *) 
$ l

---

.git/
fridge/
pantry/
readme.md
## trashcan/

~/Desktop/homework/kitchen_organizer (master *) 
$ cd trashcan
~/Desktop/homework/kitchen_organizer/trashcan (master *) 
$ mv sink/ ../
~/Desktop/homework/kitchen_organizer/trashcan (master *) 
$ cd ..
~/Desktop/homework/kitchen_organizer (master *) 
$ l

---

.git/
fridge/
pantry/
readme.md
sink/
## trashcan/

~/Desktop/homework/kitchen_organizer (master *) 
$ cd pantry
~/Desktop/homework/kitchen_organizer/pantry (master *) 
$ l

---

cans.txt
cereal.txt
## crisper-drawer/

~/Desktop/homework/kitchen_organizer/pantry (master *) 
$ mv crisper-drawer/ ../fridge/
~/Desktop/homework/kitchen_organizer/pantry (master *) 
$ cd ..
~/Desktop/homework/kitchen_organizer (master *) 
$ cd fridge/crisper-drawer/
~/Desktop/homework/kitchen_organizer/fridge/crisper-drawer (master *) 
$ touch apples
~/Desktop/homework/kitchen_organizer/fridge/crisper-drawer (master *) 
$ cd ../freezer
~/Desktop/homework/kitchen_organizer/fridge/freezer (master *) 
$ l

---

couch.txt
frozenpeas.txt
## icecream.txt

~/Desktop/homework/kitchen_organizer/fridge/freezer (master *) 
$ rm couch.txt
~/Desktop/homework/kitchen_organizer/fridge/freezer (master *) 
$ cd ..
~/Desktop/homework/kitchen_organizer/fridge (master *) 
$ l

---

crisper-drawer/
diapers.txt
freezer/
## milk.txt

~/Desktop/homework/kitchen_organizer/fridge (master *) 
$ rm diapers.txt
~/Desktop/homework/kitchen_organizer/fridge (master *) 
$ l

---

crisper-drawer/
freezer/
## milk.txt

~/Desktop/homework/kitchen_organizer/fridge (master *) 
$ cd ..
~/Desktop/homework/kitchen_organizer (master *) 
$ cd sink
~/Desktop/homework/kitchen_organizer/sink (master *) 
$ l

---

clean-dishes.txt
delete-me.txt
## dirty-dishes.txt

~/Desktop/homework/kitchen_organizer/sink (master *) 
$ rm delete-me.txt
~/Desktop/homework/kitchen_organizer/sink (master *) 
$ mkdir drying-rack
~/Desktop/homework/kitchen_organizer/sink (master *) 
$ mv clean-dishes.txt drying-rack/

**Comment by RobertAKARobin** [comment]
:+1: 
Remember to use backtics to format code when you paste it into Github -- just like on Slack.
