### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/kitchen_organizer#35]
$ ls \* -r
ls: -r: No such file or directory
cans.txt    readme.md

fridge:
diapers.txt freezer     milk.txt    trashcan

pantry:
cans.txt    cereal.txt  crisper-drawer

sink:

trashcan:
~/wdi/kitchen 
$ mv crisper-drawer fridge/
mv: rename crisper-drawer to fridge/crisper-drawer: No such file or directory
~/wdi/kitchen 
$ ls *
cans.txt    readme.md

fridge:
diapers.txt freezer     milk.txt    trashcan

pantry:
cans.txt    cereal.txt  crisper-drawer

sink:

trashcan:
~/wdi/kitchen 
$ cp pantry/crisper-drawer fridge/
cp: pantry/crisper-drawer is a directory (not copied).
~/wdi/kitchen 
$ ls *
cans.txt    readme.md

fridge:
diapers.txt freezer     milk.txt    trashcan

pantry:
cans.txt    cereal.txt  crisper-drawer

sink:

trashcan:
~/wdi/kitchen 
$ cp -R crisper-drawer fridge/
cp: crisper-drawer: No such file or directory
~/wdi/kitchen 
$ cp -R pantry/crisper-drawer fridge/
~/wdi/kitchen 
$ ls *
cans.txt    readme.md

fridge:
crisper-drawer  diapers.txt freezer     milk.txt    trashcan

pantry:
cans.txt    cereal.txt  crisper-drawer

sink:

trashcan:
~/wdi/kitchen 
$ mv -v ~/crisper-drawer ~/fridge/
mv: rename /Users/aleaq/crisper-drawer to /Users/aleaq/fridge/: No such file or directory
~/wdi/kitchen 
$ ls *
cans.txt    readme.md

fridge:
crisper-drawer  diapers.txt freezer     milk.txt    trashcan

pantry:
cans.txt    cereal.txt  crisper-drawer

sink:

trashcan:
~/wdi/kitchen 
$ mv \* ~/crisper-drawer ~/fridge
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/kitchen 
$ ls *
cans.txt    readme.md

fridge:
crisper-drawer  diapers.txt freezer     milk.txt    trashcan

pantry:
cans.txt    cereal.txt  crisper-drawer

sink:

trashcan:
~/wdi/kitchen 
$ rm -ri pantry/crisper-drawer
examine files in directory pantry/crisper-drawer? y
remove pantry/crisper-drawer/.DS_Store? y
remove pantry/crisper-drawer/lettuce.txt? y
remove pantry/crisper-drawer? y
~/wdi/kitchen 
$ ls *
cans.txt    readme.md

fridge:
crisper-drawer  diapers.txt freezer     milk.txt    trashcan

pantry:
cans.txt    cereal.txt

sink:

trashcan:
~/wdi/kitchen 
$ ls -R fridge
crisper-drawer  diapers.txt freezer     milk.txt    trashcan

fridge/crisper-drawer:
lettuce.txt

fridge/freezer:
couch.txt   frozenpeas.txt  icecream.txt

fridge/trashcan:
banana-peels.txt    chicken-bones.txt   egg-shells.txt      sink

fridge/trashcan/sink:
clean-dishes.txt    delete-me.txt       dirty-dishes.txt
~/wdi/kitchen 
$ cd crisper-drawer touch apples.txt
-bash: cd: crisper-drawer: No such file or directory
~/wdi/kitchen 
$ ls *
cans.txt    readme.md

fridge:
crisper-drawer  diapers.txt freezer     milk.txt    trashcan

pantry:
cans.txt    cereal.txt

sink:

trashcan:
~/wdi/kitchen 
$ cd ~/crisper-drawer touch apples.txt
-bash: cd: /Users/aleaq/crisper-drawer: No such file or directory
~/wdi/kitchen 
$ cd fridge
~/wdi/kitchen/fridge 
$ cd crisper-drawer touch apples.txt
~/wdi/kitchen/fridge/crisper-drawer 
$ ls *
lettuce.txt
~/wdi/kitchen/fridge/crisper-drawer 
$ touch apples.txt
~/wdi/kitchen/fridge/crisper-drawer 
$ ls *
apples.txt  lettuce.txt
~/wdi/kitchen/fridge/crisper-drawer 
$ cd freezer
-bash: cd: freezer: No such file or directory
~/wdi/kitchen/fridge/crisper-drawer 
$ cd ~/freezer
-bash: cd: /Users/aleaq/freezer: No such file or directory
~/wdi/kitchen/fridge/crisper-drawer 
$ cd .
~/wdi/kitchen/fridge/crisper-drawer 
$ cd ..
~/wdi/kitchen/fridge 
$ ls *
diapers.txt milk.txt

crisper-drawer:
apples.txt  lettuce.txt

freezer:
couch.txt   frozenpeas.txt  icecream.txt

trashcan:
banana-peels.txt    chicken-bones.txt   egg-shells.txt      sink
~/wdi/kitchen/fridge 
$ ls
crisper-drawer  diapers.txt freezer     milk.txt    trashcan
~/wdi/kitchen/fridge 
$ rm diapers.txt
~/wdi/kitchen/fridge 
$ ls
crisper-drawer  freezer     milk.txt    trashcan
~/wdi/kitchen/fridge 
$ cd ..
~/wdi/kitchen 
$ mv ~/fridge/trashcan /kitchen
mv: rename /Users/aleaq/fridge/trashcan to /kitchen: No such file or directory
~/wdi/kitchen 
$ ls
cans.txt    fridge      pantry      readme.md   sink        trashcan
~/wdi/kitchen 
$ mv /kitchen/cans.txt ~/pantry/
mv: rename /kitchen/cans.txt to /Users/aleaq/pantry/: No such file or directory
~/wdi/kitchen 
$ mv /ktichen/cans.txt /pantry/
mv: rename /ktichen/cans.txt to /pantry/: No such file or directory
~/wdi/kitchen 
$ mv /kitchen/cans.txt /kitchen/pantry
mv: rename /kitchen/cans.txt to /kitchen/pantry: No such file or directory
~/wdi/kitchen 
$ ls
cans.txt    fridge      pantry      readme.md   sink        trashcan
~/wdi/kitchen 
$ mv ~/wdi/kitchen/cans.txt ~/wdi/kitchen/pantry
~/wdi/kitchen 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/kitchen 
$ ls -R
fridge      pantry      readme.md   sink        trashcan

./fridge:
crisper-drawer  freezer     milk.txt    trashcan

./fridge/crisper-drawer:
apples.txt  lettuce.txt

./fridge/freezer:
couch.txt   frozenpeas.txt  icecream.txt

./fridge/trashcan:
banana-peels.txt    chicken-bones.txt   egg-shells.txt      sink

./fridge/trashcan/sink:
clean-dishes.txt    delete-me.txt       dirty-dishes.txt

./pantry:
cans.txt    cereal.txt

./sink:

./trashcan:
~/wdi/kitchen 
$ mv ~/wdi/kitchen/fridge/trashcan ~/wdi/kitchen/
~/wdi/kitchen 
$ ls
fridge      pantry      readme.md   trashcan
~/wdi/kitchen 
$ mv ~/wdi/kitchen/trashcan/sink ~/wdi/kitchen
~/wdi/kitchen 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/kitchen 
$ rm -i ~/wdi/kitchen/readme.md
remove /Users/aleaq/wdi/kitchen/readme.md? y
~/wdi/kitchen 
$ ls
fridge      pantry      sink        trashcan
~/wdi/kitchen 
$ ls \* -R
ls: -R: No such file or directory
fridge:
crisper-drawer  freezer     milk.txt

pantry:
cans.txt    cereal.txt

sink:
clean-dishes.txt    delete-me.txt       dirty-dishes.txt

trashcan:
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/kitchen 
$ rm ~wdi/kitchen/sink/delete-me.txt
rm: ~wdi/kitchen/sink/delete-me.txt: No such file or directory
~/wdi/kitchen 
$ rm ~/wdi/kitchen/sink/delete-me.txt
~/wdi/kitchen 
$ mkdir ~wdi/kitchen/sink/drying-rack/
mkdir: ~wdi/kitchen/sink: No such file or directory
~/wdi/kitchen 
$ ls
fridge      pantry      sink        trashcan
~/wdi/kitchen 
$ mkdir -p kitchen/sink/drying-rack
~/wdi/kitchen 
$ ls
fridge      kitchen     pantry      sink        trashcan
~/wdi/kitchen 
$ ls *
fridge:
crisper-drawer  freezer     milk.txt

kitchen:
sink

pantry:
cans.txt    cereal.txt

sink:
clean-dishes.txt    dirty-dishes.txt

trashcan:
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/kitchen 
$ mkdir /kitchen/sink/drying-rack
mkdir: /kitchen/sink: No such file or directory
~/wdi/kitchen 
$ mkdir ~/wdi/kitchen/sink/drying-rack
~/wdi/kitchen 
$ ls
fridge      pantry      sink        trashcan
~/wdi/kitchen 
$ ls *
fridge:
crisper-drawer  freezer     milk.txt

pantry:
cans.txt    cereal.txt

sink:
clean-dishes.txt    dirty-dishes.txt    drying-rack

trashcan:
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/kitchen 
$ cd sink
~/wdi/kitchen/sink 
$ mv clean-dishes.txt /drying-rack
mv: rename clean-dishes.txt to /drying-rack: Permission denied
~/wdi/kitchen/sink 
$ mv sink/clean-dishes.txt sink/drying-rack
mv: rename sink/clean-dishes.txt to sink/drying-rack: No such file or directory
~/wdi/kitchen/sink 
$ ls
clean-dishes.txt    dirty-dishes.txt    drying-rack
~/wdi/kitchen/sink 
$ mv /sink/clean-dishes.txt /sink/drying-rack
mv: rename /sink/clean-dishes.txt to /sink/drying-rack: No such file or directory
~/wdi/kitchen/sink 
$ mv ~/sink/clean-dishes.txt ~/sink/drying-rack
mv: rename /Users/aleaq/sink/clean-dishes.txt to /Users/aleaq/sink/drying-rack: No such file or directory
~/wdi/kitchen/sink 
$ ls
clean-dishes.txt    dirty-dishes.txt    drying-rack
~/wdi/kitchen/sink 
$ mv ~/wdi/kitchen/sink/clean-dishes.txt ~/wdi/kitchen/sink/drying-rack
~/wdi/kitchen/sink 
$ ls
dirty-dishes.txt    drying-rack
~/wdi/kitchen/sink 
$ cd ..
~/wdi/kitchen 
$ 
~/wdi/kitchen 
$ cd ..
~/wdi 
$ brew install git bash-completion
Warning: git-2.6.1 already installed
Warning: bash-completion-1.3 already installed
~/wdi 
$ cd ~/.bash_profile
-bash: cd: /Users/aleaq/.bash_profile: Not a directory
~/wdi 
$ atom
~/wdi 
$ cd kitchen
~/wdi/kitchen 
$ ls *
fridge:
crisper-drawer  freezer     milk.txt

pantry:
cans.txt    cereal.txt

sink:
dirty-dishes.txt    drying-rack

trashcan:
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/kitchen 
$ cd freezer
-bash: cd: freezer: No such file or directory
~/wdi/kitchen 
$ cd fridge/freezer
~/wdi/kitchen/fridge/freezer 
$ touch frozenpeas.txt icecream.txt
~/wdi/kitchen/fridge/freezer 
$ ls
couch.txt   frozenpeas.txt  icecream.txt
~/wdi/kitchen/fridge/freezer 
$ rm couch.txt
~/wdi/kitchen/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/wdi/kitchen/fridge/freezer 
$ cd ..
~/wdi/kitchen/fridge 
$ cd ..
~/wdi/kitchen 
$ ls *
fridge:
crisper-drawer  freezer     milk.txt

pantry:
cans.txt    cereal.txt

sink:
dirty-dishes.txt    drying-rack

trashcan:
banana-peels.txt    chicken-bones.txt   egg-shells.txt
~/wdi/kitchen

**Comment by mattscilipoti** [comment]
:+1:
