### ISSUE TITLE
Kibble - CLI homework

### ISSUE THREAD

**Issue by ckib16** [ga-wdi-exercises/kitchen_organizer#36]
Chris@MBAir:~/wdi$ git clone https://github.com/ga-dc/kitchen_organizer
Cloning into 'kitchen_organizer'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 16 (delta 4), reused 16 (delta 4), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.
--------------------------------------------------------------- 21:42:34
Chris@MBAir:~/wdi$ ls
Rakefile           installfest.yml    resume/
curriculum/        kitchen_organizer/ sandbox/
exercises/         projects/
--------------------------------------------------------------- 21:42:36
Chris@MBAir:~/wdi$ cd kitchen_organizer/
--------------------------------------------------------------- 21:42:39
Chris@MBAir:~/wdi/kitchen_organizer$ ls
cans.txt   fridge/    pantry/    readme.md
--------------------------------------------------------------- 21:43:07
Chris@MBAir:~/wdi/kitchen_organizer$ ls -la
total 8
drwxr-xr-x   7 Chris  staff   238B Oct 13 21:42 ./
drwxr-xr-x  11 Chris  staff   374B Oct 13 21:42 ../
drwxr-xr-x  12 Chris  staff   408B Oct 13 21:42 .git/
-rw-r--r--   1 Chris  staff     0B Oct 13 21:42 cans.txt
drwxr-xr-x   6 Chris  staff   204B Oct 13 21:42 fridge/
drwxr-xr-x   5 Chris  staff   170B Oct 13 21:42 pantry/
-rw-r--r--   1 Chris  staff   1.6K Oct 13 21:42 readme.md
--------------------------------------------------------------- 21:43:42
Chris@MBAir:~/wdi/kitchen_organizer$ rm cans.txt 
--------------------------------------------------------------- 21:44:30
Chris@MBAir:~/wdi/kitchen_organizer$ ls
fridge/    pantry/    readme.md
--------------------------------------------------------------- 21:44:31
Chris@MBAir:~/wdi/kitchen_organizer$ cd fridge
--------------------------------------------------------------- 21:45:12
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ ls
diapers.txt  freezer/     milk.txt     trashcan/
--------------------------------------------------------------- 21:45:14
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ rm diapers.txt 
--------------------------------------------------------------- 21:46:09
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ ls
freezer/  milk.txt  trashcan/
--------------------------------------------------------------- 21:46:10
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ mv trashcan/ ..
--------------------------------------------------------------- 21:46:53
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ ls
freezer/  milk.txt
--------------------------------------------------------------- 21:46:55
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ cd ..
--------------------------------------------------------------- 21:46:58
Chris@MBAir:~/wdi/kitchen_organizer$ ls
fridge/    pantry/    readme.md  trashcan/
--------------------------------------------------------------- 21:46:59
Chris@MBAir:~/wdi/kitchen_organizer$ cd trashcan/
--------------------------------------------------------------- 21:47:18
Chris@MBAir:~/wdi/kitchen_organizer/trashcan$ ls
banana-peels.txt   egg-shells.txt
chicken-bones.txt  sink/
--------------------------------------------------------------- 21:47:19
Chris@MBAir:~/wdi/kitchen_organizer/trashcan$ mv sink/ ..
--------------------------------------------------------------- 21:47:27
Chris@MBAir:~/wdi/kitchen_organizer/trashcan$ ls
banana-peels.txt   chicken-bones.txt  egg-shells.txt
--------------------------------------------------------------- 21:47:28
Chris@MBAir:~/wdi/kitchen_organizer/trashcan$ cd ..
--------------------------------------------------------------- 21:47:33
Chris@MBAir:~/wdi/kitchen_organizer$ ls
fridge/    pantry/    readme.md  sink/      trashcan/
--------------------------------------------------------------- 21:47:35
Chris@MBAir:~/wdi/kitchen_organizer$ cd pantry/
--------------------------------------------------------------- 21:48:23
Chris@MBAir:~/wdi/kitchen_organizer/pantry$ ls
cans.txt        cereal.txt      crisper-drawer/
--------------------------------------------------------------- 21:48:24
Chris@MBAir:~/wdi/kitchen_organizer/pantry$ mv crisper-drawer/ ../fridge/
--------------------------------------------------------------- 21:48:57
Chris@MBAir:~/wdi/kitchen_organizer/pantry$ cd ..
--------------------------------------------------------------- 21:49:00
Chris@MBAir:~/wdi/kitchen_organizer$ ls
fridge/    pantry/    readme.md  sink/      trashcan/
--------------------------------------------------------------- 21:49:01
Chris@MBAir:~/wdi/kitchen_organizer$ cd fridge/
--------------------------------------------------------------- 21:49:04
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ ls
crisper-drawer/ freezer/        milk.txt
--------------------------------------------------------------- 21:49:05
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ cd ..
--------------------------------------------------------------- 21:49:22
Chris@MBAir:~/wdi/kitchen_organizer$ cd pantry/
--------------------------------------------------------------- 21:49:27
Chris@MBAir:~/wdi/kitchen_organizer/pantry$ ls
cans.txt    cereal.txt
--------------------------------------------------------------- 21:49:28
Chris@MBAir:~/wdi/kitchen_organizer/pantry$ cd ..
--------------------------------------------------------------- 21:49:35
Chris@MBAir:~/wdi/kitchen_organizer$ cd sink/
--------------------------------------------------------------- 21:49:37
Chris@MBAir:~/wdi/kitchen_organizer/sink$ ls
clean-dishes.txt  delete-me.txt     dirty-dishes.txt
--------------------------------------------------------------- 21:49:38
Chris@MBAir:~/wdi/kitchen_organizer/sink$ rm delete-me.txt 
--------------------------------------------------------------- 21:49:42
Chris@MBAir:~/wdi/kitchen_organizer/sink$ ls
clean-dishes.txt  dirty-dishes.txt
--------------------------------------------------------------- 21:49:43
Chris@MBAir:~/wdi/kitchen_organizer/sink$ mkdir drying-rack
--------------------------------------------------------------- 21:50:16
Chris@MBAir:~/wdi/kitchen_organizer/sink$ ls
clean-dishes.txt  dirty-dishes.txt  drying-rack/
--------------------------------------------------------------- 21:50:18
Chris@MBAir:~/wdi/kitchen_organizer/sink$ mv clean-dishes.txt drying-rack/
--------------------------------------------------------------- 21:50:37
Chris@MBAir:~/wdi/kitchen_organizer/sink$ ls
dirty-dishes.txt  drying-rack/
--------------------------------------------------------------- 21:50:38
Chris@MBAir:~/wdi/kitchen_organizer/sink$ cd drying-rack/
--------------------------------------------------------------- 21:50:42
Chris@MBAir:~/wdi/kitchen_organizer/sink/drying-rack$ ls
clean-dishes.txt
--------------------------------------------------------------- 21:50:42
Chris@MBAir:~/wdi/kitchen_organizer/sink/drying-rack$ cd ..
--------------------------------------------------------------- 21:50:50
Chris@MBAir:~/wdi/kitchen_organizer/sink$ cd ..
--------------------------------------------------------------- 21:50:53
Chris@MBAir:~/wdi/kitchen_organizer$ ls -lr
total 8
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:47 trashcan/
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:50 sink/
-rw-r--r--  1 Chris  staff   1.6K Oct 13 21:42 readme.md
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:48 pantry/
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:48 fridge/
--------------------------------------------------------------- 21:50:59
Chris@MBAir:~/wdi/kitchen_organizer$ ls -lR
total 8
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:48 fridge/
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:48 pantry/
-rw-r--r--  1 Chris  staff   1.6K Oct 13 21:42 readme.md
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:50 sink/
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:47 trashcan/

./fridge:
total 0
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 crisper-drawer/
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:42 freezer/
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 milk.txt

./fridge/crisper-drawer:
total 0
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 lettuce.txt

./fridge/freezer:
total 0
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 couch.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 frozenpeas.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 icecream.txt

./pantry:
total 0
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 cans.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 cereal.txt

./sink:
total 0
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 dirty-dishes.txt
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:50 drying-rack/

./sink/drying-rack:
total 0
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 clean-dishes.txt

./trashcan:
total 0
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 banana-peels.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 chicken-bones.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 egg-shells.txt
--------------------------------------------------------------- 21:51:39
Chris@MBAir:~/wdi/kitchen_organizer$ ls -laR
total 8
drwxr-xr-x   8 Chris  staff   272B Oct 13 21:47 ./
drwxr-xr-x  11 Chris  staff   374B Oct 13 21:42 ../
drwxr-xr-x  12 Chris  staff   408B Oct 13 21:42 .git/
drwxr-xr-x   5 Chris  staff   170B Oct 13 21:48 fridge/
drwxr-xr-x   4 Chris  staff   136B Oct 13 21:48 pantry/
-rw-r--r--   1 Chris  staff   1.6K Oct 13 21:42 readme.md
drwxr-xr-x   4 Chris  staff   136B Oct 13 21:50 sink/
drwxr-xr-x   5 Chris  staff   170B Oct 13 21:47 trashcan/

./.git:
total 40
drwxr-xr-x  12 Chris  staff   408B Oct 13 21:42 ./
drwxr-xr-x   8 Chris  staff   272B Oct 13 21:47 ../
-rw-r--r--   1 Chris  staff    23B Oct 13 21:42 HEAD
-rw-r--r--   1 Chris  staff   312B Oct 13 21:42 config
-rw-r--r--   1 Chris  staff    73B Oct 13 21:42 description
drwxr-xr-x  11 Chris  staff   374B Oct 13 21:42 hooks/
-rw-r--r--   1 Chris  staff   1.7K Oct 13 21:42 index
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 info/
drwxr-xr-x   4 Chris  staff   136B Oct 13 21:42 logs/
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 objects/
-rw-r--r--   1 Chris  staff   107B Oct 13 21:42 packed-refs
drwxr-xr-x   5 Chris  staff   170B Oct 13 21:42 refs/

./.git/hooks:
total 80
drwxr-xr-x  11 Chris  staff   374B Oct 13 21:42 ./
drwxr-xr-x  12 Chris  staff   408B Oct 13 21:42 ../
-rwxr-xr-x   1 Chris  staff   478B Oct 13 21:42 applypatch-msg.sample*
-rwxr-xr-x   1 Chris  staff   896B Oct 13 21:42 commit-msg.sample*
-rwxr-xr-x   1 Chris  staff   189B Oct 13 21:42 post-update.sample*
-rwxr-xr-x   1 Chris  staff   424B Oct 13 21:42 pre-applypatch.sample*
-rwxr-xr-x   1 Chris  staff   1.6K Oct 13 21:42 pre-commit.sample*
-rwxr-xr-x   1 Chris  staff   1.3K Oct 13 21:42 pre-push.sample*
-rwxr-xr-x   1 Chris  staff   4.8K Oct 13 21:42 pre-rebase.sample*
-rwxr-xr-x   1 Chris  staff   1.2K Oct 13 21:42 prepare-commit-msg.sample*
-rwxr-xr-x   1 Chris  staff   3.5K Oct 13 21:42 update.sample*

./.git/info:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  12 Chris  staff   408B Oct 13 21:42 ../
-rw-r--r--   1 Chris  staff   240B Oct 13 21:42 exclude

./.git/logs:
total 8
drwxr-xr-x   4 Chris  staff   136B Oct 13 21:42 ./
drwxr-xr-x  12 Chris  staff   408B Oct 13 21:42 ../
-rw-r--r--   1 Chris  staff   180B Oct 13 21:42 HEAD
drwxr-xr-x   4 Chris  staff   136B Oct 13 21:42 refs/

./.git/logs/refs:
total 0
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:42 ./
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:42 ../
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 heads/
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 remotes/

./.git/logs/refs/heads:
total 8
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:42 ../
-rw-r--r--  1 Chris  staff   180B Oct 13 21:42 master

./.git/logs/refs/remotes:
total 0
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:42 ../
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 origin/

./.git/logs/refs/remotes/origin:
total 8
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 ../
-rw-r--r--  1 Chris  staff   180B Oct 13 21:42 HEAD

./.git/objects:
total 0
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ./
drwxr-xr-x  12 Chris  staff   408B Oct 13 21:42 ../
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 05/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 0a/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 0c/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 2e/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 37/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 3d/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 48/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 66/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 75/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 77/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 97/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 9c/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 a5/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 bc/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 e1/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 e6/
drwxr-xr-x   2 Chris  staff    68B Oct 13 21:42 info/
drwxr-xr-x   2 Chris  staff    68B Oct 13 21:42 pack/

./.git/objects/05:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   536B Oct 13 21:42 6fea7027413d397b6fdbb519746388065c497f

./.git/objects/0a:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff    56B Oct 13 21:42 989b874f56ec00afbdcc8d906f58fced3cadcd

./.git/objects/0c:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   128B Oct 13 21:42 4373c96f535ea3b57b315d3cceb0731c359d4a

./.git/objects/2e:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   162B Oct 13 21:42 922b742418f46a730fd5eac6d03361d137169a

./.git/objects/37:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   150B Oct 13 21:42 c8f07b882858410c3332391536a3a1c18b075f

./.git/objects/3d:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   149B Oct 13 21:42 7b9b07d32f4edbd55d89c025306b117274881e

./.git/objects/48:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff    82B Oct 13 21:42 324d784d08ae087973961bbd129e5b0ac0a51e

./.git/objects/66:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   138B Oct 13 21:42 fa07dd6970aadb408e2c6b1b1e32ce0dffcc1d

./.git/objects/75:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   118B Oct 13 21:42 d8c4dc2a7f4078fd4839e84600d364f34d383b

./.git/objects/77:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   150B Oct 13 21:42 96c5167c2722940a5deba3714651c44d3890a0

./.git/objects/97:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff    80B Oct 13 21:42 4dfc2b25ac67433cb04474fe1c5871cc6f5a69

./.git/objects/9c:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   613B Oct 13 21:42 c76a511e8c9d732a09b79bb05821665d3d5162

./.git/objects/a5:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   104B Oct 13 21:42 aef9962ec42b9bd85b268e90b0b2e2624a08ba

./.git/objects/bc:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   608B Oct 13 21:42 5e4bb4ab9262af596e7ef4739765781d382d85

./.git/objects/e1:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff   163B Oct 13 21:42 15c26256795bc93dffa8c1535a7e8902551740

./.git/objects/e6:
total 8
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../
-r--r--r--   1 Chris  staff    15B Oct 13 21:42 9de29bb2d1d6434b8b29ae775ad8c2e48c5391

./.git/objects/info:
total 0
drwxr-xr-x   2 Chris  staff    68B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../

./.git/objects/pack:
total 0
drwxr-xr-x   2 Chris  staff    68B Oct 13 21:42 ./
drwxr-xr-x  20 Chris  staff   680B Oct 13 21:42 ../

./.git/refs:
total 0
drwxr-xr-x   5 Chris  staff   170B Oct 13 21:42 ./
drwxr-xr-x  12 Chris  staff   408B Oct 13 21:42 ../
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 heads/
drwxr-xr-x   3 Chris  staff   102B Oct 13 21:42 remotes/
drwxr-xr-x   2 Chris  staff    68B Oct 13 21:42 tags/

./.git/refs/heads:
total 8
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:42 ../
-rw-r--r--  1 Chris  staff    41B Oct 13 21:42 master

./.git/refs/remotes:
total 0
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:42 ../
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 origin/

./.git/refs/remotes/origin:
total 8
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 ../
-rw-r--r--  1 Chris  staff    32B Oct 13 21:42 HEAD

./.git/refs/tags:
total 0
drwxr-xr-x  2 Chris  staff    68B Oct 13 21:42 ./
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:42 ../

./fridge:
total 0
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:48 ./
drwxr-xr-x  8 Chris  staff   272B Oct 13 21:47 ../
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 crisper-drawer/
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:42 freezer/
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 milk.txt

./fridge/crisper-drawer:
total 0
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:42 ./
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:48 ../
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 lettuce.txt

./fridge/freezer:
total 0
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:42 ./
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:48 ../
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 couch.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 frozenpeas.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 icecream.txt

./pantry:
total 0
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:48 ./
drwxr-xr-x  8 Chris  staff   272B Oct 13 21:47 ../
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 cans.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 cereal.txt

./sink:
total 0
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:50 ./
drwxr-xr-x  8 Chris  staff   272B Oct 13 21:47 ../
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 dirty-dishes.txt
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:50 drying-rack/

./sink/drying-rack:
total 0
drwxr-xr-x  3 Chris  staff   102B Oct 13 21:50 ./
drwxr-xr-x  4 Chris  staff   136B Oct 13 21:50 ../
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 clean-dishes.txt

./trashcan:
total 0
drwxr-xr-x  5 Chris  staff   170B Oct 13 21:47 ./
drwxr-xr-x  8 Chris  staff   272B Oct 13 21:47 ../
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 banana-peels.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 chicken-bones.txt
-rw-r--r--  1 Chris  staff     0B Oct 13 21:42 egg-shells.txt
--------------------------------------------------------------- 21:52:02
Chris@MBAir:~/wdi/kitchen_organizer$ ls -R
fridge/    pantry/    readme.md  sink/      trashcan/

./fridge:
crisper-drawer/ freezer/        milk.txt

./fridge/crisper-drawer:
lettuce.txt

./fridge/freezer:
couch.txt       frozenpeas.txt  icecream.txt

./pantry:
cans.txt    cereal.txt

./sink:
dirty-dishes.txt  drying-rack/

./sink/drying-rack:
clean-dishes.txt

./trashcan:
banana-peels.txt   chicken-bones.txt  egg-shells.txt
--------------------------------------------------------------- 21:52:07
Chris@MBAir:~/wdi/kitchen_organizer$ cd fridge/
--------------------------------------------------------------- 21:52:53
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ touch apples.txt
--------------------------------------------------------------- 21:52:59
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ ls
apples.txt      crisper-drawer/ freezer/        milk.txt
--------------------------------------------------------------- 21:53:01
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ mv apples.txt crisper-drawer/
--------------------------------------------------------------- 21:53:29
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ ls
crisper-drawer/ freezer/        milk.txt
--------------------------------------------------------------- 21:53:31
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ ls -R
crisper-drawer/ freezer/        milk.txt

./crisper-drawer:
apples.txt   lettuce.txt

./freezer:
couch.txt       frozenpeas.txt  icecream.txt
--------------------------------------------------------------- 21:53:35
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ cd freezer/
--------------------------------------------------------------- 21:53:51
Chris@MBAir:~/wdi/kitchen_organizer/fridge/freezer$ rm couch.txt 
--------------------------------------------------------------- 21:53:57
Chris@MBAir:~/wdi/kitchen_organizer/fridge/freezer$ ls
frozenpeas.txt  icecream.txt
--------------------------------------------------------------- 21:53:58
Chris@MBAir:~/wdi/kitchen_organizer/fridge/freezer$ cd ...
-bash: cd: ...: No such file or directory
--------------------------------------------------------------- 21:54:01
Chris@MBAir:~/wdi/kitchen_organizer/fridge/freezer$ cd ..
--------------------------------------------------------------- 21:54:03
Chris@MBAir:~/wdi/kitchen_organizer/fridge$ cd ..
--------------------------------------------------------------- 21:54:06
Chris@MBAir:~/wdi/kitchen_organizer$ ls -R
fridge/    pantry/    readme.md  sink/      trashcan/

./fridge:
crisper-drawer/ freezer/        milk.txt

./fridge/crisper-drawer:
apples.txt   lettuce.txt

./fridge/freezer:
frozenpeas.txt  icecream.txt

./pantry:
cans.txt    cereal.txt

./sink:
dirty-dishes.txt  drying-rack/

./sink/drying-rack:
clean-dishes.txt

./trashcan:
banana-peels.txt   chicken-bones.txt  egg-shells.txt
--------------------------------------------------------------- 21:54:08

**Comment by RobertAKARobin** [comment]
:+1:
