### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by ajohnson052** [ga-wdi-exercises/kitchen_organizer#38]
~/wdi/exercises/kitchen_organizer (master)
$ mv ./fridge/trashcan ./
~/wdi/exercises/kitchen_organizer (master *)
$ mv ./trashcan/sink ./
~/wdi/exercises/kitchen_organizer (master *)
$ mv pantry/crisper-drawer fridge/
~/wdi/exercises/kitchen_organizer (master *)
$ touch fridge/crisper-drawer/apples.txt
~/wdi/exercises/kitchen_organizer (master *)
$ rm cans.txt
~/wdi/exercises/kitchen_organizer (master *)
$ rm fridge/diapers.txt
~/wdi/exercises/kitchen_organizer (master *)
$ rm fridge/freezer/couch.txt
~/wdi/exercises/kitchen_organizer (master *)
$ mkdir sink/drying-rack/
~/wdi/exercises/kitchen_organizer (master *)
$ rm sink/delete-me.txt
~/wdi/exercises/kitchen_organizer (master *)
$ mv sink/clean-dishes.txt sink/drying-rack/

**Comment by jsm13** [comment]
:+1:
