### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by clarktsc39** [ga-wdi-exercises/kitchen_organizer#4]
$ cd kitchen_organizer-master/
~/Downloads/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/Downloads/kitchen_organizer-master 
$ ls -a
.       cans.txt    pantry
..      fridge      readme.md
~/Downloads/kitchen_organizer-master 
$ open readme.md
~/Downloads/kitchen_organizer-master 
$ open readme.md
~/Downloads/kitchen_organizer-master 
$ cd kitchen
-bash: cd: kitchen: No such file or directory
~/Downloads/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/Downloads/kitchen_organizer-master 
$ cd fridge
~/Downloads/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/Downloads/kitchen_organizer-master/fridge 
$ cd trashcan
~/Downloads/kitchen_organizer-master/fridge/trashcan 
$ ls
banana-peels.txt    egg-shells.txt
chicken-bones.txt   sink
~/Downloads/kitchen_organizer-master/fridge/trashcan 
$ ls kitchen
ls: kitchen: No such file or directory
~/Downloads/kitchen_organizer-master/fridge/trashcan 
$ ls -a
.           chicken-bones.txt
..          egg-shells.txt
banana-peels.txt    sink
~/Downloads/kitchen_organizer-master/fridge/trashcan 
$ cd ..
~/Downloads/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/Downloads/kitchen_organizer-master/fridge 
$ cd freezer
~/Downloads/kitchen_organizer-master/fridge/freezer 
$ cd ../
~/Downloads/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/Downloads/kitchen_organizer-master/fridge 
$ rm diapers.txt
~/Downloads/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt    trashcan
~/Downloads/kitchen_organizer-master/fridge 
$ mv trashcan ../
~/Downloads/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt
~/Downloads/kitchen_organizer-master/fridge 
$ cd ..
~/Downloads/kitchen_organizer-master 
$ ls
cans.txt    pantry      trashcan
fridge      readme.md
~/Downloads/kitchen_organizer-master 
$ cd trashcan/
~/Downloads/kitchen_organizer-master/trashcan 
$ ls
banana-peels.txt    egg-shells.txt
chicken-bones.txt   sink
~/Downloads/kitchen_organizer-master/trashcan 
$ mv sink ../
~/Downloads/kitchen_organizer-master/trashcan 
$ cd ..
~/Downloads/kitchen_organizer-master 
$ ls
cans.txt    pantry      sink
fridge      readme.md   trashcan
~/Downloads/kitchen_organizer-master 
$ cd sink
~/Downloads/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    dirty-dishes.txt
delete-me.txt
~/Downloads/kitchen_organizer-master/sink 
$ rm delete-me.txt 
~/Downloads/kitchen_organizer-master/sink 
$ mkdir drying-rack
~/Downloads/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    drying-rack
dirty-dishes.txt
~/Downloads/kitchen_organizer-master/sink 
$ mv clean-dishes.txt 
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/Downloads/kitchen_organizer-master/sink 
$ mv clean-dishes.txt drying-rack/
~/Downloads/kitchen_organizer-master/sink 
$ ls
dirty-dishes.txt    drying-rack
~/Downloads/kitchen_organizer-master/sink 
$ cd drying-rack/
~/Downloads/kitchen_organizer-master/sink/drying-rack 
$ ls
clean-dishes.txt
~/Downloads/kitchen_organizer-master/sink/drying-rack 
$ cd ../../
~/Downloads/kitchen_organizer-master 
$ ls
cans.txt    pantry      sink
fridge      readme.md   trashcan
~/Downloads/kitchen_organizer-master 
$ cd trashcan
~/Downloads/kitchen_organizer-master/trashcan 
$ ls
banana-peels.txt    egg-shells.txt
chicken-bones.txt
~/Downloads/kitchen_organizer-master/trashcan 
$ cd ..
~/Downloads/kitchen_organizer-master 
$ mv cans.txt pantry/
~/Downloads/kitchen_organizer-master 
$ ls
fridge      readme.md   trashcan
pantry      sink
~/Downloads/kitchen_organizer-master 
$ cd pantry
~/Downloads/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt  crisper-drawer
~/Downloads/kitchen_organizer-master/pantry 
$ mv crisper-drawer/ ../fridge
~/Downloads/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt
~/Downloads/kitchen_organizer-master/pantry 
$ cd ..
~/Downloads/kitchen_organizer-master 
$ ls
fridge      readme.md   trashcan
pantry      sink
~/Downloads/kitchen_organizer-master 
$ cd fridge/
~/Downloads/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt
~/Downloads/kitchen_organizer-master/fridge 
$ cd crisper-drawer/
~/Downloads/kitchen_organizer-master/fridge/crisper-drawer 
$ ls
lettuce.txt
~/Downloads/kitchen_organizer-master/fridge/crisper-drawer 
$ touch apples.txt
~/Downloads/kitchen_organizer-master/fridge/crisper-drawer 
$ ls
apples.txt  lettuce.txt
~/Downloads/kitchen_organizer-master/fridge/crisper-drawer 
$ cd ..
~/Downloads/kitchen_organizer-master/fridge 
$ cd freezer
~/Downloads/kitchen_organizer-master/fridge/freezer 
$ ls
couch.txt   frozenpeas.txt  icecream.txt
~/Downloads/kitchen_organizer-master/fridge/freezer 
$ rm couch.txt
~/Downloads/kitchen_organizer-master/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/Downloads/kitchen_organizer-master/fridge/freezer 
$

**Comment by amaseda** [comment]
:+1:
