### ISSUE TITLE
Andre Shonubi - HW - 1- CLI

### ISSUE THREAD

**Issue by codedre** [ga-wdi-exercises/kitchen_organizer#40]
~/wdi/kitchen_organizer (master *) 
$ mv pantry/crisper-drawer/ fridge/
~/wdi/kitchen_organizer (master *) 
$ rm -r fridge/diapers.txt fridge/freezer/couch.txt 
~/wdi/kitchen_organizer (master *) 
$ mkdir sink/drying-rack
~/wdi/kitchen_organizer (master *) 
$ rm -r sink/delete-me.txt 
~/wdi/kitchen_organizer (master *) 
$ mv sink/clean-dishes.txt sink/drying-rack/
~/wdi/kitchen_organizer (master *) 
$ touch fridge/crisper-drawer/apples.txt
~/wdi/kitchen_organizer (master *) 
$ ls -lr
total 8
drwxr-xr-x  5 andreshonubi  staff   170 Oct 13 23:09 trashcan
drwxr-xr-x  4 andreshonubi  staff   136 Oct 13 23:17 sink
-rw-r--r--  1 andreshonubi  staff  1630 Oct 13 23:01 readme.md
drwxr-xr-x  4 andreshonubi  staff   136 Oct 13 23:11 pantry
drwxr-xr-x  5 andreshonubi  staff   170 Oct 13 23:15 fridge
~/wdi/kitchen_organizer (master *) 
$ ls -lR
total 8
drwxr-xr-x  5 andreshonubi  staff   170 Oct 13 23:15 fridge
drwxr-xr-x  4 andreshonubi  staff   136 Oct 13 23:11 pantry
-rw-r--r--  1 andreshonubi  staff  1630 Oct 13 23:01 readme.md
drwxr-xr-x  4 andreshonubi  staff   136 Oct 13 23:17 sink
drwxr-xr-x  5 andreshonubi  staff   170 Oct 13 23:09 trashcan

./fridge:
total 0
drwxr-xr-x  4 andreshonubi  staff  136 Oct 13 23:18 crisper-drawer
drwxr-xr-x  4 andreshonubi  staff  136 Oct 13 23:15 freezer
-rw-r--r--  1 andreshonubi  staff    0 Oct 13 23:01 milk.txt

./fridge/crisper-drawer:
total 0
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:18 apples.txt
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:01 lettuce.txt

./fridge/freezer:
total 0
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:01 frozenpeas.txt
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:01 icecream.txt

./pantry:
total 0
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:01 cans.txt
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:01 cereal.txt

./sink:
total 0
-rw-r--r--  1 andreshonubi  staff    0 Oct 13 23:01 dirty-dishes.txt
drwxr-xr-x  3 andreshonubi  staff  102 Oct 13 23:17 drying-rack

./sink/drying-rack:
total 0
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:01 clean-dishes.txt

./trashcan:
total 0
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:01 banana-peels.txt
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:01 chicken-bones.txt
-rw-r--r--  1 andreshonubi  staff  0 Oct 13 23:01 egg-shells.txt
~/wdi/kitchen_organizer (master *) 
$

**Comment by mattscilipoti** [comment]
:+1:
