### ISSUE TITLE
Pengelly - HW - CLI

### ISSUE THREAD

**Issue by jenpen** [ga-wdi-exercises/kitchen_organizer#41]
Last login: Tue Oct 13 23:08:02 on ttys000
~ 
$ cd wdi/exercises/cli/kitchen
~/wdi/exercises/cli/kitchen 
$ pwd
/Users/Jen/wdi/exercises/cli/kitchen
~/wdi/exercises/cli/kitchen 
$ rm cans.txt fridge/trashcan/sink/delete-me.txt fridge/diapers.txt fridge/freezer/couch.txt
~/wdi/exercises/cli/kitchen 
$ mv fridge/trashcan trashcan
~/wdi/exercises/cli/kitchen 
$ mv trashcan/sink sink
~/wdi/exercises/cli/kitchen 
$ mv pantry/crisper-drawer fridge/crisper-drawer
~/wdi/exercises/cli/kitchen 
$ mkdir sink/drying-rack
~/wdi/exercises/cli/kitchen 
$ mv sink/clean-dishes.txt sink/drying-rack/clean-dishes.txt
~/wdi/exercises/cli/kitchen 
$ touch fridge/crisper-drawer/apples.txt
~/wdi/exercises/cli/kitchen 
$ ls -lR
total 0
drwxr-xr-x@ 5 Jen  staff  170 Oct 13 23:11 fridge
drwxr-xr-x@ 4 Jen  staff  136 Oct 13 23:11 pantry
drwxr-xr-x@ 4 Jen  staff  136 Oct 13 23:12 sink
drwxr-xr-x@ 5 Jen  staff  170 Oct 13 23:10 trashcan

./fridge:
total 0
drwxr-xr-x@ 4 Jen  staff  136 Oct 13 23:12 crisper-drawer
drwxr-xr-x@ 4 Jen  staff  136 Oct 13 23:10 freezer
-rwxr-xr-x@ 1 Jen  staff    0 Oct 13 23:06 milk.txt

./fridge/crisper-drawer:
total 0
-rw-r--r--  1 Jen  staff  0 Oct 13 23:12 apples.txt
-rwxr-xr-x@ 1 Jen  staff  0 Oct 13 23:06 lettuce.txt

./fridge/freezer:
total 0
-rwxr-xr-x@ 1 Jen  staff  0 Oct 13 23:06 frozenpeas.txt
-rwxr-xr-x@ 1 Jen  staff  0 Oct 13 23:06 icecream.txt

./pantry:
total 0
-rwxr-xr-x@ 1 Jen  staff  0 Oct 13 23:06 cans.txt
-rwxr-xr-x@ 1 Jen  staff  0 Oct 13 23:06 cereal.txt

./sink:
total 0
-rwxr-xr-x@ 1 Jen  staff    0 Oct 13 23:06 dirty-dishes.txt
drwxr-xr-x  3 Jen  staff  102 Oct 13 23:12 drying-rack

./sink/drying-rack:
total 0
-rwxr-xr-x@ 1 Jen  staff  0 Oct 13 23:06 clean-dishes.txt

./trashcan:
total 0
-rwxr-xr-x@ 1 Jen  staff  0 Oct 13 23:06 banana-peels.txt
-rwxr-xr-x@ 1 Jen  staff  0 Oct 13 23:06 chicken-bones.txt
-rwxr-xr-x@ 1 Jen  staff  0 Oct 13 23:06 egg-shells.txt
~/wdi/exercises/cli/kitchen 
$

**Comment by andrewsunglaekim** [comment]
:+1:
