### ISSUE TITLE
Ly - Kitchen Organizer HW

### ISSUE THREAD

**Issue by Ly900** [ga-wdi-exercises/kitchen_organizer#42]
Comfort: 4
Completeness: 5
1. rm -r cans.txt pantry/crisper-drawer/ fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/clean-dishes.txt fridge/trashcan/sink/delete-me.txt
2. mkdir -p  ~/wdi/exercises/kitchen2/fridge/crisper-drawer/lettuce.txt ~/wdi/exercises/kitchen2/fridge/crisper-drawer/apples.txt
3. mkdir -p ~/wdi/exercises/kitchen2/fridge/trashcan/sink/drying-rack/clean-dishes.txt
4. mv ~/wdi/exercises/kitchen2/fridge/trashcan/sink ~/wdi/exercises/kitchen2/fridge/trashcan ~/wdi/exercises/kitchen2/

**Comment by andrewsunglaekim** [comment]
:+1:
