### ISSUE TITLE
CLI Homework

### ISSUE THREAD

**Issue by brittonwalker** [ga-wdi-exercises/kitchen_organizer#43]
Comfort-level: 4
Completeness: 5

1 mv fridge/trashcan/sink . 
2 mv fridge/trashcan .
3 mkdir sink/drying-rack
4 mv sink/clean-dishes.txt sink/drying-rack/
5 rm -R pantry/crisper-drawer cans.txt fridge/diapers.txt fridge/freezer/couch.txt sink/delete-me.txt
6 mkdir fridge/crisper-drawer
7 touch fridge/crisper-drawer/apples.txt fridge/crisper-drawer/lettuce.txt

**Comment by nolds9** [comment]
:+1:
