### ISSUE TITLE
Day 2 CLI HW

### ISSUE THREAD

**Issue by dttruong** [ga-wdi-exercises/kitchen_organizer#44]
comfort: 3.5
completeness: 5

mv kitchen_organizer-master/ kitchen/
rm fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt
rm cans.txt
mv fridge/trashcan/ kitchen/
mv pantry/crisper-drawer/ fridge/
touch fridge/crisper-drawer/apples.txt
mkdir sink/drying-rack
mv sink/clean-dishes.txt sink/drying-rack/

**Comment by nolds9** [comment]
:+1:
