### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by andrewjohnson8819** [ga-wdi-exercises/kitchen_organizer#45]
~/wdi/homework/kitchen_organizer/kitchen 
$ rm cans.txt
~/wdi/homework/kitchen_organizer/kitchen 
$ cd pantry
~/wdi/homework/kitchen_organizer/kitchen/pantry 
$ mv crisper-drawer ~/wdi/homework/kitchen_organizer/kitchen/fridge
~/wdi/homework/kitchen_organizer/kitchen/pantry 
$ cd fridge
-bash: cd: fridge: No such file or directory
~/wdi/homework/kitchen_organizer/kitchen/pantry 
$ cd ..
~/wdi/homework/kitchen_organizer/kitchen 
$ cd fridge
~/wdi/homework/kitchen_organizer/kitchen/fridge 
$ rm diapers.txt
~/wdi/homework/kitchen_organizer/kitchen/fridge 
$ mv trashcan ../
~/wdi/homework/kitchen_organizer/kitchen/fridge 
$ cd crisper-drawer/
~/wdi/homework/kitchen_organizer/kitchen/fridge/crisper-drawer 
$ touch apples.txt
~/wdi/homework/kitchen_organizer/kitchen/fridge/crisper-drawer 
$ cd ..
~/wdi/homework/kitchen_organizer/kitchen/fridge 
$ cd freezer
~/wdi/homework/kitchen_organizer/kitchen/fridge/freezer 
$ rm couch.txt
~/wdi/homework/kitchen_organizer/kitchen/fridge/freezer 
$ cd ..
~/wdi/homework/kitchen_organizer/kitchen/fridge 
$ cd ..
~/wdi/homework/kitchen_organizer/kitchen 
$ cd trashcan
~/wdi/homework/kitchen_organizer/kitchen/trashcan 
$ mv sink ../
~/wdi/homework/kitchen_organizer/kitchen/trashcan 
$ cd ..
~/wdi/homework/kitchen_organizer/kitchen 
$ cd sink
~/wdi/homework/kitchen_organizer/kitchen/sink 
$ rm delete-me.txt
~/wdi/homework/kitchen_organizer/kitchen/sink 
$ mkdir drying-rack
~/wdi/homework/kitchen_organizer/kitchen/sink 
$ mv clean-dishes.txt drying-rack/
~/wdi/homework/kitchen_organizer/kitchen/sink 
$

**Comment by jsm13** [comment]
:+1:
