### ISSUE TITLE
Kitchen HW

### ISSUE THREAD

**Issue by tomiteo** [ga-wdi-exercises/kitchen_organizer#46]
(Sorry it's not _all_ here--when I went to copy it at the end somehow the beginning commands were excluded)

timothys-MacBook% ls
freezer     milk.txt
timothys-MacBook% cd freezer 
timothys-MacBook% rm couch.txt 
timothys-MacBook% cd ../..
timothys-MacBook% ls
fridge      pantry      readme.md   trashcan
timothys-MacBook% cd trashcan 
timothys-MacBook% ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt      sink
timothys-MacBook% mv sink ..
timothys-MacBook% ls
banana-peels.txt    chicken-bones.txt   egg-shells.txt
timothys-MacBook% cd ..
timothys-MacBook% ls
fridge      pantry      readme.md   sink        trashcan
timothys-MacBook% cd sink 
timothys-MacBook% ls
clean-dishes.txt    delete-me.txt       dirty-dishes.txt
timothys-MacBook% rm delete-me.txt 
timothys-MacBook% mkdir drying-rack
timothys-MacBook% ls
clean-dishes.txt    dirty-dishes.txt    drying-rack
timothys-MacBook% mv clean-dishes.txt drying-rack 
timothys-MacBook% ls
dirty-dishes.txt    drying-rack
timothys-MacBook% cd ..
timothys-MacBook% ls
fridge      pantry      readme.md   sink        trashcan
timothys-MacBook% cd pantry 
timothys-MacBook% ls
cans.txt    cereal.txt  crisper-drawer
timothys-MacBook% mv crisper-drawer ..
timothys-MacBook% ls
cans.txt    cereal.txt
timothys-MacBook% ls
cans.txt    cereal.txt
timothys-MacBook% cd ..
timothys-MacBook% ls
crisper-drawer  fridge      pantry      readme.md   sink        trashcan
timothys-MacBook% mw crisper-drawer fridge 
zsh: command not found: mw
timothys-MacBook% ls
crisper-drawer  fridge      pantry      readme.md   sink        trashcan
timothys-MacBook% mv crisper-drawer fridge 
timothys-MacBook% ls
fridge      pantry      readme.md   sink        trashcan
timothys-MacBook% cd f
cd: no such file or directory: f
timothys-MacBook% cd fridge 
timothys-MacBook% ls
crisper-drawer  freezer     milk.txt
timothys-MacBook% cd crisper-drawer 
timothys-MacBook% ls
lettuce.txt
timothys-MacBook% touch apples.txt
timothys-MacBook% ls
apples.txt  lettuce.txt
timothys-MacBook% cd ..
timothys-MacBook% cd ..
timothys-MacBook% cd -
~/wdi/kitchen/kitchen_organizer/fridge
timothys-MacBook% ls
crisper-drawer  freezer     milk.txt
timothys-MacBook%

**Comment by jshawl** [comment]
:+1: check out https://www.iterm2.com/ and enable infinite scrollback. Alternatively, you can `less ~/.bash_history` to view your history.

Also, make sure to use backticks when pasting code on github:

```
timothys-MacBook% ls
crisper-drawer freezer milk.txt
timothys-MacBook%
```

**Comment by tomiteo** [comment]
thanks, will do in the future
