### ISSUE TITLE
Samir - CLI HW

### ISSUE THREAD

**Issue by samir-acle** [ga-wdi-exercises/kitchen_organizer#47]
$ mv fridge/trashcan/sink/ .
$ mv fridge/trashcan .
$ rm fridge/diapers.txt fridge/freezer/couch.txt trashcan/sink/delete-me.txt
$ cd ..
$ rm sink/delete-me.txt
$ mv pantry/crisper-drawer/ fridge/
$ cd sink
$ mkdir drying-rack
$ mv clean-dishes.txt drying-rack/
$ cd ..
$ rm cans.txt
$ cd crisper-drawer
$ touch apples.txt

**Comment by RobertAKARobin** [comment]
:+1:
