### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by tylercrosse** [ga-wdi-exercises/kitchen_organizer#5]
mv pantry/crisper-drawer/ fridge
mv fridge/trashcan .
mv kitchen/trashcan/sink .
mkdir /sink/drying-rack/
mv sink/clean-dishes.txt sink/drying-rack/
mv cans.txt apples.txt
mv apples.txt fridge/crisper-drawer/
rm fridge/diapers.txt fridge/freezer/couch.txt sink/delete-me.txt

**Comment by amaseda** [comment]
:+1:
