### ISSUE TITLE
Day 2 CLI Homework

### ISSUE THREAD

**Issue by ddayporter** [ga-wdi-exercises/kitchen_organizer#51]
Comfort: 3.5
Completeness: 5*

*I completely forgot to submit this so I'm not sure I can give it a 100% complete! Also it didn't explicitly say to copy the ls -lR output but I figured why not. I feel comfortable with the way I did it but I feel like there must be a way to do it in fewer moves.. I wasn't sure if a cd counted as a move, so I included them all in the below but I hope they don't actually count because that makes it super long. 

~/homework/kitchen_organizer (master) 
$ mkdir kitchen 
~/homework/kitchen_organizer (master) 
$ mv fridge pantry kitchen 
~/homework/kitchen_organizer (master *) 
$ cd kitchen
~/homework/kitchen_organizer/kitchen (master *)  
$ cd fridge
~/homework/kitchen_organizer/kitchen/fridge (master *)  
$ rm diapers.txt 
~/homework/kitchen_organizer/kitchen/fridge (master *) 
$ mv trashcan ../ 
~/homework/kitchen_organizer/kitchen/fridge (master *) 
$ cd freezer
~/homework/kitchen_organizer/kitchen/fridge/freezer (master *) 
$ rm couch.txt 
~/homework/kitchen_organizer/kitchen/fridge/freezer (master *) 
$ cd ..
~/homework/kitchen_organizer/kitchen/fridge (master *) 
$ cd ..
~/homework/kitchen_organizer/kitchen (master *) 
$ cd trashcan
~/homework/kitchen_organizer/kitchen/trashcan (master *) 
$ mv sink ../ 
~/homework/kitchen_organizer/kitchen/trashcan (master *) 
$ cd ..
~/homework/kitchen_organizer/kitchen (master *) 
$ cd sink
~/homework/kitchen_organizer/kitchen/sink (master *) 
$ rm delete-me.txt 
~/homework/kitchen_organizer/kitchen/sink (master *) 
$ mkdir drying-rack 
~/homework/kitchen_organizer/kitchen/sink (master *) 
$ mv clean-dishes.txt drying-rack 
~/homework/kitchen_organizer/kitchen/sink (master *)  
$ cd ..
~/homework/kitchen_organizer/kitchen (master *) 
$ cd pantry
~/homework/kitchen_organizer/kitchen/pantry (master *) 
$ mv crisper-drawer ../fridge/ 
$ cd ..
~/homework/kitchen_organizer/kitchen (master *) 
$ cd fridge
~/homework/kitchen_organizer/kitchen/fridge (master *) 
$ cd crisper-drawer
~/homework/kitchen_organizer/kitchen/fridge/crisper-drawer (master *) 
$ touch apples.txt 
~/homework/kitchen_organizer/kitchen/fridge/crisper-drawer (master *) 
$ cd ../../
~/homework/kitchen_organizer/kitchen (master *) 
$ ls -lR
total 0
drwxr-xr-x  5 rachel2  staff  170 Oct 13 21:14 fridge
drwxr-xr-x  4 rachel2  staff  136 Oct 13 21:14 pantry
drwxr-xr-x  4 rachel2  staff  136 Oct 13 21:12 sink
drwxr-xr-x  5 rachel2  staff  170 Oct 13 21:10 trashcan

./fridge:
total 0
drwxr-xr-x  4 rachel2  staff  136 Oct 13 21:16 crisper-drawer
drwxr-xr-x  4 rachel2  staff  136 Oct 13 21:09 freezer
-rw-r--r--  1 rachel2  staff    0 Oct 13 20:44 milk.txt

./fridge/crisper-drawer:
total 0
-rw-r--r--  1 rachel2  staff  0 Oct 13 21:16 apples.txt
-rw-r--r--  1 rachel2  staff  0 Oct 13 20:44 lettuce.txt

./fridge/freezer:
total 0
-rw-r--r--  1 rachel2  staff  0 Oct 13 20:44 frozenpeas.txt
-rw-r--r--  1 rachel2  staff  0 Oct 13 20:44 icecream.txt

./pantry:
total 0
-rw-r--r--  1 rachel2  staff  0 Oct 13 20:44 cans.txt
-rw-r--r--  1 rachel2  staff  0 Oct 13 20:44 cereal.txt

./sink:
total 0
-rw-r--r--  1 rachel2  staff    0 Oct 13 20:44 dirty-dishes.txt
drwxr-xr-x  3 rachel2  staff  102 Oct 13 21:12 drying-rack

./sink/drying-rack:
total 0
-rw-r--r--  1 rachel2  staff  0 Oct 13 20:44 clean-dishes.txt

./trashcan:
total 0
-rw-r--r--  1 rachel2  staff  0 Oct 13 20:44 banana-peels.txt
-rw-r--r--  1 rachel2  staff  0 Oct 13 20:44 chicken-bones.txt
-rw-r--r--  1 rachel2  staff  0 Oct 13 20:44 egg-shells.txt

**Comment by mattscilipoti** [comment]
:+1:
