### ISSUE TITLE
HW

### ISSUE THREAD

**Issue by jnichols300** [ga-wdi-exercises/kitchen_organizer#52]
cd pantry
mv crisper-drawer ../fridge/
cd ..
rm cans.txt
cd trashcan
mv sink ../../kitchen/
cd ..
rm diapers.txt
cd freezer
rm couch.txt
cd ..
cd sink
rm delete-me.txt
mkdir drying-rack
mv clean-dishes.txt /drying-rack

**Comment by andrewsunglaekim** [comment]
:+1:
