### ISSUE TITLE
kitchen_organizer H dubs

### ISSUE THREAD

**Issue by JohnWPark** [ga-wdi-exercises/kitchen_organizer#53]
Comfort: 3
Completeness: 5

cd kitchen/

rm fridge/diapers.txt fridge/freezer/couch.txt fridge/trashcan/sink/delete-me.txt

mv cans.txt pantry/

mv fridge/trashcan/ .

mv trashcan/sink/ .

mkdir sink/drying-rack/

mv clean-dishes.txt drying-rack/

mv pantry/crisper-drawer fridge/

touch fridge/crisper-drawer/apples.txt

Still not 100% comfortable with CLI and git.  Will spend extra time on it until I'm feeling like a 5.

**Comment by andrewsunglaekim** [comment]
You'll get there, CLI and git become second nature with more exposure. You'll have plenty of exposure throughout this class.
