### ISSUE TITLE
HW2 - Kitchen Organizer

### ISSUE THREAD

**Issue by shindigira** [ga-wdi-exercises/kitchen_organizer#55]
$ mkdir drying-rack
$ mv clean-dishes.txt /drying-rack
$ rm cans.txt
$ cd pantry
$ mv crisper-drawer ../fridge/
$ cd ..
$ rm diapers.txt
$ cd trashcan
$ mv sink ../../kitchen/
$ cd ../freezer
$ rm couch.txt
$ cd ../sink
$ rm delete-me.txt

**Comment by nolds9** [comment]
:+1:
