### ISSUE TITLE
Chrystal's Kitchen Homework

### ISSUE THREAD

**Issue by CBanks813** [ga-wdi-exercises/kitchen_organizer#58]
$ cd ..
~/wdi 
$ cd Kitchen
~/wdi/Kitchen 
$ ls
fridge      pantry      sink        trashcan
~/wdi/Kitchen 
$ ls
fridge      pantry      sink        trashcan
~/wdi/Kitchen 
$ cd fridge
~/wdi/Kitchen/fridge 
$ ls
crisper-drawer  freezer     milk.txt
~/wdi/Kitchen/fridge 
$ 

Comfort: This was pretty easy(5)
Completeness: I think it is correct. (4)

**Comment by adambray** [comment]
:+1: 

Looks good!
