### ISSUE TITLE
M. Shofner - Week 1 Homework - Kitchen Organizer

### ISSUE THREAD

**Issue by MarkhamShofner** [ga-wdi-exercises/kitchen_organizer#59]
Kitchen Organizer Submission. Thought it had gone in during initial date. 

~/wdi/homework/week1/command_line/kitchen_organizer (master) 
$ ./pantry mv crisper-drawer ./fridge
-bash: ./pantry: is a directory
~/wdi/homework/week1/command_line/kitchen_organizer (master) 

$ mv ./pantry/crisper-drawer ./fridge
~/wdi/homework/week1/command_line/kitchen_organizer (master *) 

$ touch ./fridge/crisper-drawer/apples.txt
~/wdi/homework/week1/command_line/kitchen_organizer (master *) 

$ rm ./fridge/freezer/couch.txt ./fridge/trashcan/sink/delete-me.txt ./fridge/diapers.txt ./cans.txt
~/wdi/homework/week1/command_line/kitchen_organizer (master *) 

$ mv ./fridge/trashcan .
~/wdi/homework/week1/command_line/kitchen_organizer (master *) 

$ mv ./trashcan/sink .
~/wdi/homework/week1/command_line/kitchen_organizer (master *) 

$ mkdir ./sink/drying-rack
~/wdi/homework/week1/command_line/kitchen_organizer (master *) 

$ mv ./sink/clean-dishes.txt ./sink/drying-rack
~/wdi/homework/week1/command_line/kitchen_organizer (master *) 

$ mv cans.txt pantry

**Comment by mattscilipoti** [comment]
:+1:
