### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by joe-gz** [ga-wdi-exercises/kitchen_organizer#6]
$ cd kitchen_organizer-master/
$ mkdir kitchen
$ mv pantry fridge kitchen
$ mv cans.txt kitchen/pantry/
$ mv fridge/trashcan/sink .
$ mv fridge/trashcan .
$ mv pantry/crisper-drawer ~/wdi/exercises/kitchen_organizer-master/kitchen/fridge/
$ rm fridge/diapers.txt fridge/freezer/couch.txt sink/delete-me.txt
$ touch fridge/crisper-drawer/apples.txt
$ mkdir sink/drying-rack
$ mv sink/clean-dishes.txt sink/drying-rack/

**Comment by ebirving** [comment]
👍
