### ISSUE TITLE
HW Day 1: kitchen_organizer-master

### ISSUE THREAD

**Issue by alifrumin** [ga-wdi-exercises/kitchen_organizer#8]
~ 
$ ls
Applications    Downloads   Music       deleteme    pizza
Desktop     Library     Pictures    fundamentals    wdi
Documents   Movies      Public      funny_things
~ 
$ cd wdi
~/wdi 
$ ls
exercises   projects    sandbox
~/wdi 
$ cd exercises
~/wdi/exercises 
$ ls
kitchen_organizer-master    kitchen_organizer-master copy
~/wdi/exercises 
$ cd kitchen_organizer_master
-bash: cd: kitchen_organizer_master: No such file or directory
~/wdi/exercises 
$ cd kitchen_organizer-master
~/wdi/exercises/kitchen_organizer-master 
$ ls
cans.txt    fridge      pantry      readme.md
~/wdi/exercises/kitchen_organizer-master 
$ rm cans.txt
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
diapers.txt freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv diapers.txt trashcan/
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd trashcan/
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ ls
banana-peels.txt    diapers.txt     sink
chicken-bones.txt   egg-shells.txt
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ ..
-bash: ..: command not found
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ ls
banana-peels.txt    diapers.txt     sink
chicken-bones.txt   egg-shells.txt
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ ../
-bash: ../: is a directory
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ ls
banana-peels.txt    diapers.txt     sink
chicken-bones.txt   egg-shells.txt
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ cd fridge
-bash: cd: fridge: No such file or directory
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ cd/
-bash: cd/: No such file or directory
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ cd /
/ 
$ ls
Applications            etc
Library             home
Network             installer.failurerequests
System              net
Users               private
Volumes             sbin
bin             tmp
cores               usr
dev             var
/ 
$ cd ~
~ 
$ ls
Applications    Downloads   Music       deleteme    pizza
Desktop     Library     Pictures    fundamentals    wdi
Documents   Movies      Public      funny_things
~ 
$ cd wdi
~/wdi 
$ ls
exercises   projects    sandbox
~/wdi 
$ cd exercises/
~/wdi/exercises 
$ ls
kitchen_organizer-master    kitchen_organizer-master copy
~/wdi/exercises 
$ cd kitchen_organizer-master
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md
~/wdi/exercises/kitchen_organizer-master 
$ cd fridge/
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv trashcan/..
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd trashcan/
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ ls
banana-peels.txt    diapers.txt     sink
chicken-bones.txt   egg-shells.txt
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ mv sink ../
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ ls
banana-peels.txt    diapers.txt
chicken-bones.txt   egg-shells.txt
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ ls
banana-peels.txt    diapers.txt
chicken-bones.txt   egg-shells.txt
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ cd-
-bash: cd-: command not found
~/wdi/exercises/kitchen_organizer-master/fridge/trashcan 
$ cd -
/Users/alifrumin/wdi/exercises/kitchen_organizer-master/fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt    sink        trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ sink ../
-bash: sink: command not found
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv sink ../
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd freezer
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ ls
couch.txt   frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ rm couch.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ cd -
/Users/alifrumin/wdi/exercises/kitchen_organizer-master/fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv trashcan../kitchen_organizer-master
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv trashcan/..
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt    trashcan
~/wdi/exercises/kitchen_organizer-master/fridge 
$ mv trashcan/ ../
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd-
-bash: cd-: command not found
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd -
/Users/alifrumin/wdi/exercises/kitchen_organizer-master/fridge/freezer
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ cd -
/Users/alifrumin/wdi/exercises/kitchen_organizer-master/fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd -
/Users/alifrumin/wdi/exercises/kitchen_organizer-master/fridge/freezer
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ cd - fridge
/Users/alifrumin/wdi/exercises/kitchen_organizer-master/fridge
~/wdi/exercises/kitchen_organizer-master/fridge 
$ ls
freezer     milk.txt
~/wdi/exercises/kitchen_organizer-master/fridge 
$ cd - pantry
/Users/alifrumin/wdi/exercises/kitchen_organizer-master/fridge/freezer
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ ls
frozenpeas.txt  icecream.txt
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ cd~
-bash: cd~: command not found
~/wdi/exercises/kitchen_organizer-master/fridge/freezer 
$ cd ~
~ 
$ ls
Applications    Downloads   Music       deleteme    pizza
Desktop     Library     Pictures    fundamentals    wdi
Documents   Movies      Public      funny_things
~ 
$ cd wdi
~/wdi 
$ ls
exercises   projects    sandbox
~/wdi 
$ cd exercises/
~/wdi/exercises 
$ ls
kitchen_organizer-master    kitchen_organizer-master copy
~/wdi/exercises 
$ cd kitchen_organizer-master
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd pantry
~/wdi/exercises/kitchen_organizer-master/pantry 
$ ls
cans.txt    cereal.txt  crisper-drawer
~/wdi/exercises/kitchen_organizer-master/pantry 
$ mv crisper-drawer/ ../fridge/
~/wdi/exercises/kitchen_organizer-master/pantry 
$ touch apples.txt
~/wdi/exercises/kitchen_organizer-master/pantry 
$ mv apples.txt ../fridge/crisper-drawer/
~/wdi/exercises/kitchen_organizer-master/pantry 
$ cd -
/Users/alifrumin/wdi/exercises/kitchen_organizer-master
~/wdi/exercises/kitchen_organizer-master 
$ ls
fridge      pantry      readme.md   sink        trashcan
~/wdi/exercises/kitchen_organizer-master 
$ cd sink
~/wdi/exercises/kitchen_organizer-master/sink 
$ rm delete-me.txt 
~/wdi/exercises/kitchen_organizer-master/sink 
$ mkdir drying rack
~/wdi/exercises/kitchen_organizer-master/sink 
$ rm drying rack
rm: drying: is a directory
rm: rack: is a directory
~/wdi/exercises/kitchen_organizer-master/sink 
$ mv clean-dishes.txt drying/
~/wdi/exercises/kitchen_organizer-master/sink 
$

**Comment by ebirving** [comment]
👍
