### ISSUE TITLE
Day 1 HW

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/kitchen_organizer#9]
~/wdi/exercise/kitchen_organizer-master 
$ mv ~/wdi/exercise/kitchen_organizer-master/fridge/trashcan ~/wdi/exercise/kitchen_organizer-master/trashcan
~/wdi/exercise/kitchen_organizer-master 
$ mv ~/wdi/exercise/kitchen_organizer-master/trashcan/sink ~/wdi/exercise/kitchen_organizer-master/sink
~/wdi/exercise/kitchen_organizer-master 
$ mv pantry/crisper-drawer fridge/crisper-drawer
~/wdi/exercise/kitchen_organizer-master 
$ cd fridge
~/wdi/exercise/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  diapers.txt freezer     milk.txt
~/wdi/exercise/kitchen_organizer-master/fridge 
$ rm diapers.txt
~/wdi/exercise/kitchen_organizer-master/fridge 
$ ls
crisper-drawer  freezer     milk.txt
~/wdi/exercise/kitchen_organizer-master/fridge 
$ cd freezer
~/wdi/exercise/kitchen_organizer-master/fridge/freezer 
$ ls
couch.txt   frozenpeas.txt  icecream.txt
~/wdi/exercise/kitchen_organizer-master/fridge/freezer 
$ rm couch.txt
~/wdi/exercise/kitchen_organizer-master/fridge/freezer 
$ cd ..
~/wdi/exercise/kitchen_organizer-master/fridge 
$ cd crisper-drawer
~/wdi/exercise/kitchen_organizer-master/fridge/crisper-drawer 
$ touch apples.txt
~/wdi/exercise/kitchen_organizer-master/fridge/crisper-drawer 
$ cd ~/wdi/exercise/kitchen_organizer-master/
~/wdi/exercise/kitchen_organizer-master 
$ ls
cans.txt    pantry      sink
fridge      readme.md   trashcan
~/wdi/exercise/kitchen_organizer-master 
$ rm cans.txt
~/wdi/exercise/kitchen_organizer-master 
$ cd sink
~/wdi/exercise/kitchen_organizer-master/sink 
$ ls
clean-dishes.txt    delete-me.txt       dirty-dishes.txt
~/wdi/exercise/kitchen_organizer-master/sink 
$ rm delete-me.txt
~/wdi/exercise/kitchen_organizer-master/sink 
$ mkdir drying-rack
~/wdi/exercise/kitchen_organizer-master/sink 
$ mv clean-dishes.txt drying-rack/clean-dishes.txt
~/wdi/exercise/kitchen_organizer-master/sink

**Comment by adambray** [comment]
:+1:
